<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"url", description: tr("URL"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("String containing the URL with want to change."),examples:[{code:"https://en.wikipedia.org/wiki/URL"},{code:"</br>https://fingerprints.bablosoft.com/#testing"},{code:"</br>https://rucaptcha.com/in.php?key=1abc234de56fab7c89012d34e56fa7b8</br>&method=userrecaptcha&version=enterprise&action=verify</br>&min_score=0.3</br>&googlekey=6LfZil0UAAAAAAdm1Dpzsw9q0F11-bmervx9g5fE&pageurl=http://mysite.com/page/"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"protocol", description:tr("Protocol/Scheme") + ". " + tr("Can be blank"), default_selector: "string", variants: ["*<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>","https","http","wss","ws","ftps","ftp","file"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The scheme of accessing a resource, in most cases, means a network protocol."), examples:[{code:"https"},{code:"http"},{code:"ws"},{code:"ftp"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"*", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"username", description:tr("Username") + ". " + tr("Can be blank"), default_selector: "string", variants: ["*<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The username used to access the resource."), examples:[{code:"user1"},{code:"login321"},{code:"myname"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"*", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"password", description:tr("Password") + ". " + tr("Can be blank"), default_selector: "string", variants: ["*<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The password for the specified user."), examples:[{code:"pass123"},{code:"mypassword111"},{code:"goodpass"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"*", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"host", description:tr("Host") + ". " + tr("Can be blank"), default_selector: "string", variants: ["*<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Hostname or ip (IPv4 or IPv6)."), examples:[{code:"en.wikipedia.org"},{code:"fingerprints.bablosoft.com"},{code:"rucaptcha.com"},{code:"127.0.0.1"},{code:"[2a00:1450:4025:401::67]"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"*", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"port", description:tr("Port") + ". " + tr("Can be blank"), default_selector: "string", variants: ["*<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>","80","443","21","70"], value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Resource port."), examples:[{code:80},{code:443},{code:21},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"*", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"path", description:tr("Path") + ". " + tr("Can be blank"), default_selector: "string", variants: ["*<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The path specifying information about the location of the resource."), examples:[{code:"/wiki/URL"},{code:"/"},{code:"/in.php"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"*", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"query", description:tr("Query") + ". " + tr("Can be blank"), default_selector: "string", variants: ["*<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Object or query string.") + " " + tr("The query is the part of the URL that starts with the \"?\" character, parameters are separated by \"&\", and parameter name and value are separated by \"=\"."), examples:[{code:"{\"foo\":\"bar\"}"},{code:"</br>{\"query\":\"string\"}"},{code:"</br>sitekey=10000000-ffff-ffff-ffff-000000000001&pageurl=http://mysite.com/register"},{code:"</br>" + tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"</br>" + "*", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"hash", description:tr("Fragment") + ". " + tr("Can be blank"), default_selector: "string", variants: ["*<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Fragment is the part of the URL that starts with the \"#\" character and can indicate a title within a document or the id attribute of an element. Following the link with the fragment, the browser will open the page and move the window to the specified element."), examples:[{code:"info"},{code:"testing"},{code:"solving_recaptcha_enterprise"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"*", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#block_start').html())({id:"Additional", name: tr("Additional settings"), description: ""}) %>
<%= _.template($('#input_constructor').html())({id:"base_url", description: tr("Base URL"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The URL used when the main URL is relative."),examples:[{code:"https://en.wikipedia.org"},{code:"https://fingerprints.bablosoft.com"},{code:"https://rucaptcha.com"}]} }) %>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check">
	<input type="checkbox" id="Check" checked="checked" style="margin-left:25px"/> <label for="Check" class="tr">Normalize URL before changing</label>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check2">
	<input type="checkbox" id="Check2" checked="checked" style="margin-left:25px"/> <label for="Check2" class="tr">Complete action with fail if an invalid URL is specified</label>
</span></div>
<%= _.template($('#block_end').html())() %>
<%= _.template($('#variable_constructor').html())({id:"Save", description:tr("Variable to save the result"), default_variable: "CHANGED_URL", help: {description: tr("Variable in which, after successful execution of the action, the final URL will be written."), examples:[{code:"https://en.wikipedia.org/wiki/URL"},{code:"</br>http://fingerprints.bablosoft.com/#testing"},{code:"</br>http://rucaptcha.com/in.php?key=1abc234de56fab7c89012d34e56fa7b8</br>&method=userrecaptcha&version=enterprise&action=verify</br>&min_score=0.3</br>&googlekey=6LfZil0UAAAAAAdm1Dpzsw9q0F11-bmervx9g5fE&pageurl=http://mysite.com/page"}]} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Change the items of the specified URL.</div>
	<div class="tooltip-paragraph-fold"><span class="tr">This action will return a string containing the changed URL.</span> <span class="tr">You can learn more about URL in <a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://en.wikipedia.org/wiki/URL');return false">Wiki</a>.</span></div>
	<div class="tr tooltip-paragraph-fold">Specify new values for the items to be changed in the URL, specify <code>"*"</code> if the item needs to be removed, leave the field blank if the item does not need to be changed.</div>
	<div class="tr tooltip-paragraph-fold">The query must be specified as an object, where the key is the name of the parameter and the value is the value of the parameter. Or as a string, in which parameters are separated by "&", and the parameter name and its value are separated by "=".</div>
	<div class="tooltip-paragraph-fold"><span class="tr">Before changing, you can normalize the URL by activating the corresponding parameter in the additional settings, or use the "Normalize URL" action for flexible normalization.</span> <span class="tr">You can learn more about the URL normalization in <a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://en.wikipedia.org/wiki/URI_normalization');return false">Wiki</a>.</span></div>
	<div class="tr tooltip-paragraph-fold">You can parse a link to items using the "Parse URL" action.</div>
	<div class="tr tooltip-paragraph-fold">You can generate a link from items using the "Generate URL" action.</div>
	<div class="tr tooltip-paragraph-last-fold">If an invalid URL is specified, the thread will stop with fail message. If you want to continue thread, use "Ignore errors" action, or deactivate the corresponding parameter in the additional settings.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
