<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"string1", description:tr("String") + " 1. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The string to be concatenated with other strings."),examples:[{code:tr("Just sample text")},{code:"Test text"},{code:"string"},{code:tr("Empty string"), description: tr("The parameters \"String 2\", \"String 3\", \"List of strings\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"string2", description:tr("String") + " 2. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The string to be concatenated with other strings."),examples:[{code:tr("Just sample text")},{code:"Test text"},{code:"string"},{code:tr("Empty string"), description: tr("The parameters \"String 1\", \"String 3\", \"List of strings\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"string3", description:tr("String") + " 3. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The string to be concatenated with other strings."),examples:[{code:tr("Just sample text")},{code:"Test text"},{code:"string"},{code:tr("Empty string"), description: tr("The parameters \"String 1\", \"String 2\", \"List of strings\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"strings_list", description:tr("List of strings") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("List of strings to be concatenated.") + " " + tr("As a list, you can use a string consisting of strings, separated by commas."),examples:[{code:"Just sample text,Test text,string"},{code:"Just sample text, Test text, string"},{code:"[\"Just sample text\", \"Test text\", \"string\"]"},{code:tr("Empty string"), description: tr("The parameters \"String 1\", \"String 2\", \"String 3\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"separator", description: tr("Separator") + ". " + tr("Can be blank"), default_selector: "string", value_string: "", help: {description: tr("Separator to insert between the concatenated strings."),examples:[{code:'","',description:tr("Just sample text") + ",Test text,string"},{code:'" "',description:tr("Just sample text") + " Test text string"},{code:'", "',description:tr("Just sample text") + ", Test text, string"},{code:tr("Empty string"), description: tr("Concatenate strings without separator")}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"Save", description:tr("Variable to save the result"), default_variable: "RESULT_STRING", help: {description: tr("Variable in which, after successful execution of the action, the final string will be written."), examples:[{code:"String1String2String3"},{code:"Text test string"},{code:"TestTest"}]} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Concatenate multiple strings into one.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
