<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"string1", description:tr("String") + " 1. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The string to be concatenated with other strings."),examples:[{code:tr("Just sample text")},{code:"Test text"},{code:"string"},{code:tr("Empty string"), description: tr("The parameters \"String 2\", \"String 3\", \"List of strings\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"string2", description:tr("String") + " 2. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The string to be concatenated with other strings."),examples:[{code:tr("Just sample text")},{code:"Test text"},{code:"string"},{code:tr("Empty string"), description: tr("The parameters \"String 1\", \"String 3\", \"List of strings\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"string3", description:tr("String") + " 3. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The string to be concatenated with other strings."),examples:[{code:tr("Just sample text")},{code:"Test text"},{code:"string"},{code:tr("Empty string"), description: tr("The parameters \"String 1\", \"String 2\", \"List of strings\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"strings_list", description:tr("List of strings") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("List of strings to be concatenated.") + " " + tr("As a list, you can use a string consisting of strings, separated by commas."),examples:[{code:"Just sample text,Test text,string"},{code:"Just sample text, Test text, string"},{code:"[\"Just sample text\", \"Test text\", \"string\"]"},{code:tr("Empty string"), description: tr("The parameters \"String 1\", \"String 2\", \"String 3\" will be used")}]} }) %>
<%= _.template($('#block_start').html())({id:"Additional", name: tr("Additional settings"), description: ""}) %>
<%= _.template($('#input_constructor').html())({id:"separator", description: tr("Separator"), default_selector: "string", value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Separator to insert between the concatenated strings."),examples:[{code:'","',description:tr("Just sample text") + ",Test text,string"},{code:'" "',description:tr("Just sample text") + " Test text string"},{code:'", "',description:tr("Just sample text") + ", Test text, string"},{code:tr("Empty string"), description: tr("Concatenate strings without separator")}]} }) %>
<%= _.template($('#block_end').html())() %>
<%= _.template($('#variable_constructor').html())({id:"Save", description:tr("Variable to save the result"), default_variable: "RESULT_STRING", help: {description: tr("Variable in which, after successful execution of the action, the final string will be written."), examples:[{code:"String1String2String3"},{code:"Text test string"},{code:"TestTest"}]} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Concatenate multiple strings into one.</div>
	<div class="tr tooltip-paragraph-fold">This action will return a string composed of all the specified strings.</div>
	<div class="tr tooltip-paragraph-fold">For example, if the parameters "String 1" and "String 2" are specified, the values of which are respectively <code>"Just example"</code> and <code>" string"</code>, then the action will return <code>"Just example string"</code>.</div>
	<div class="tr tooltip-paragraph-fold">Strings from separate fields and a list are added to a general list of strings that will be concatenated.</div>
	<div class="tr tooltip-paragraph-fold">For example, if a string is specified in the "String 1" field and a list of 4 strings is specified in the "List of strings" field, then 5 strings will be concatenated.</div>
	<div class="tr tooltip-paragraph-fold">If some of the parameters ("String 1", "String 2", "String 3", "List of strings") are not specified, all parameters will be used except for them.</div>
	<div class="tr tooltip-paragraph-fold">For example, if "List of strings" is not specified, then the list will be formed from the parameters "String 1" and "String 2" and "String 3". If the parameters "String 1", "String 2", "String 3" are empty, then the "List of strings" will be used. If all parameters are specified, then all of them will be used.</div>
	<div class="tr tooltip-paragraph-fold">The order of concating the fields is as follows "String 1", "String 2", "String 3", "List of strings".</div>
	<div class="tr tooltip-paragraph-fold">The list can be created using actions from the "List" module.</div>
	<div class="tr tooltip-paragraph-last-fold">By default, strings are concatenated without a separator, but this can be changed by specifying the "Separator" parameter located in the additional settings.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
