<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"item1", description:tr("Item") + " 1. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The item to add to the CSV string."),examples:[{code:tr("Just sample text")},{code:5},{code:true},{code:tr("Empty string"), description: tr("The parameters \"Item 2\", \"Item 3\", \"List of items\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"item2", description:tr("Item") + " 2. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The item to add to the CSV string."),examples:[{code:tr("Just sample text")},{code:5},{code:true},{code:tr("Empty string"), description: tr("The parameters \"Item 1\", \"Item 3\", \"List of items\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"item3", description:tr("Item") + " 3. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The item to add to the CSV string."),examples:[{code:tr("Just sample text")},{code:5},{code:true},{code:tr("Empty string"), description: tr("The parameters \"Item 1\", \"Item 2\", \"List of items\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"items_list", description:tr("List of items") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("List of items to add to the CSV string.") + " " + tr("As a list, you can use a string consisting of strings, separated by commas."),examples:[{code:tr("Just sample text") + ",Test text,string"},{code:tr("Just sample text") + ", Test text, string"},{code:"[\"" + tr("Just sample text") + "\", \"Test text\", \"string\"]"},{code:tr("Empty string"), description: tr("The parameters \"Item 1\", \"Item 2\", \"Item 3\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"separator", description: tr("Separator"), default_selector: "string", value_string: ",", help: {description: tr("Separator to insert between elements of CSV string."),examples:[{code:'","',description:tr("Just sample text") + ",Test text,string"},{code:'" "',description:tr("Just sample text") + " Test text string"},{code:'", "',description:tr("Just sample text") + ", Test text, string"},{code:tr("Empty string"), description: '","'}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"Save", description:tr("Variable to save the result"), default_variable: "CSV_STRING", help: {description: tr("Variable in which, after successful execution of the action, the CSV string will be written."), examples:[{code:"login:password"},{code:"id,name,login"},{code:tr("Just sample text") + ";Test text;string"}]} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Create CSV string from multiple items.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
