_SMS.VakSmsApi.prototype.getRawSite = function(site){
	var sites = {
		"Other": "ot",
		"VK": "mr",
		"Mail.ru Group": "mr",
		"Qiwi": "qw",
		"Yandex": "ya",
		"Tencent QQ": "qq",
		"Netflix": "nf",
		"LINE Messenger": "lm",
		"Steam": "st",
		"Tinder": "td",
		"KakaoTalk": "kt",
		"Yalla": "ll",
		"TikTok": "tk",
		"WeChat": "wc",
		"Aol": "ao",
		"Yahoo": "yh",
		"PayPal": "pp",
		"McDonalds": "md",
		"Airbnb": "ab",
		"Discord": "dc",
		"Google": "gl",
		"Viber": "vi",
		"Facebook": "fb",
		"ProtonMail": "pm",
		"Telegram": "tg",
		"WhatsApp": "wa",
		"Uber": "ub",
		"Microsoft": "ms",
		"Instagram": "ig",
		"YooMoney": "ym",
		"WebMoney": "wm",
		"Nike": "nk",
		"Twitter": "tw",
		"Aliexpress": "ai",
		"LinkedIN": "ln",
		"Imo": "im",
		"Amazon": "am",
		"Magnit": "mg",
		"Badoo": "bd",
		"Blockchain": "bc",
		"Mamba": "mb",
		"MeetMe": "mm",
		"Burger King": "bk",
		"FarPost": "fp",
		"Plenty of Fish": "pf",
		"32red": "rd",
		"eBay": "eb",
		"Papara": "pr",
		"Naver": "nv",
		"Moteplassen": "mp",
		"Monese": "me",
		"1Cupis": "cp",
		"Samokat": "sk",
		"iHerb": "ih",
		"Paysafecard": "pc",
		"Insurance": "strh",
		"Coinut": "cn",
		"ZdravCity": "zc",
		"Beget": "bg",
		"Move": "mo",
		"Wildberries": "wb",
		"Drom.ru": "dr",
		"Booking": "bo",
		"OZON": "oz",
		"Clubhouse": "ch",
		"Pingpongx": "px",
		"Cita Previa": "ca",
		"Grindr": "gi",
		"Sbermarket": "sm",
		"ALLES Bonus": "sb",
		"METRO": "eo",
		"GroupMe": "gm",
		"Revolut": "rt",
		"Bunq": "bq",
		"CoinBase": "cb",
		"Mozen": "mz",
		"Vkusvill": "vv",
		"MVideo": "mv",
		"Getcontact": "gt",
		"Socpublic": "sp",
		"Contact-sys": "cs",
		"Signal": "sg",
		"TradingView": "tv",
		"Spaces": "si",
		"Drive2": "de",
		"Atlas": "as",
		"Deliveroo": "do",
		"Battle": "bt",
		"Boxberry": "bx",
		"SPAR": "sr",
		"Kinoservisy": "ks",
		"Miratorg": "mt",
		"Magnolia": "mn",
		"Lenta": "lt",
		"SportMaster": "sa",
		"Avito": "av",
		"BlaBlaCar": "bb",
		"DrugVokrug": "dv",
		"Vernyi": "vn",
		"Rambler": "rm",
		"Premium.one": "ta",
		"Perekrestok": "pk",
		"5ka": "pt"
	};
	return _is_nilb(sites[site]) ? sites["Other"] : sites[site];
};