_SMS.VakSmsApi.prototype.getRawSite = function(site){
	var sites = {
        "VK": "mr",
        "WhatsApp": "wa",
        "Viber": "vi",
        "Telegram": "tg",
        "WeChat": "wc",
        "Google": "gl",
        "Facebook": "fb",
        "Instagram": "ig",
        "Microsoft": "ms",
        "Twitter": "tw",
        "Uber": "ub",
        "Yahoo": "yh",
        "KakaoTalk": "kt",
        "Aol": "ao",
        "Naver": "nv",
        "Avito": "av",
        "Yandex": "ya",
        "Steam": "st",
        "Tinder": "td",
        "Imo": "im",
        "TikTok": "tk",
        "DrugVokrug": "dv",
        "5ka": "pt",
        "Discord": "dc",
        "ProtonMail": "pm",
        "Grindr": "gi",
        "LINE Messenger": "lm",
        "Tencent QQ": "qq",
        "Magnit": "mg",
        "Netflix": "nf",
        "Amazon": "am",
        "OZON": "oz",
        "BlaBlaCar": "bb",
        "Nike": "nk",
        "Qiwi": "qw",
        "OLX": "ox",
        "Airbnb": "ab",
        "MeetMe": "mm",
        "LinkedIN": "ln",
        "Yalla": "ll",
        "Perekrestok": "pk",
        "Drom.ru": "dr",
        "McDonalds": "md",
        "HQ Trivia": "hq",
        "SportMaster": "sa",
        "Papara": "pr",
        "eBay": "eb",
        "PayPal": "pp",
        "Samokat": "sk",
        "Rambler": "rm",
        "Wildberries": "wb",
        "Burger King": "bk",
        "Lenta": "lt",
        "CoinBase": "cb",
        "DodoPizza": "dp",
        "MVideo": "mv",
        "Vernyi": "vn",
        "Premium.one": "ta",
        "Douyin": "du",
        "Miratorg": "mt",
        "Karusel": "kl",
        "Magnolia": "mn",
        "MTS CashBack": "mc",
        "Deliveroo": "do",
        "Clubhouse": "ch",
        "Monese": "me",
        "Mail.ru Group": "mr",
        "TradingView": "tv",
        "Cita Previa": "ca",
        "Vkusvill": "vv",
        "Aliexpress": "ai",
        "32red": "rd",
        "Blockchain": "bc",
        "Signal": "sg",
        "Beget": "bg",
        "WebMoney": "wm",
        "ZdravCity": "zc",
        "Badoo": "bd",
        "Paysafecard": "pc",
        "BIP Messenger": "bp",
        "1Cupis": "cp",
        "YooMoney": "ym",
        "Spaces": "si",
        "FarPost": "fp",
        "OkCupid": "oc",
        "Plenty of Fish": "pf",
        "iHerb": "ih",
        "KFC": "kf",
        "SPAR": "sr",
        "Drive2": "de",
        "Getcontact": "gt",
        "METRO": "eo",
        "ALLES Bonus": "sb",
        "Bumble": "bm",
        "Coinut": "cn",
        "KazanExpress": "ke",
        "Sbermarket": "sm",
        "budget4me-34": "bgp"
    };
	if(!sites.hasOwnProperty(site)){
		this.errorHandler('UNSUPPORTED_SITE', site);
	};
	return sites[site];
};