_SMS.SmsPvaApi.prototype.getRawCountry = function(country){
	var countries = {
		"Any": "",
		"RU": "RU",
        "UA": "UA",
        "KZ": "KZ",
        "GB": "UK",
        "DE": "DE",
        "PL": "PL",
        "EE": "EE",
        "SE": "SE",
        "ID": "ID",
        "RO": "RO",
        "LT": "LT",
        "NL": "NL",
        "LV": "LV",
        "ES": "ES",
        "FR": "FR",
        "MD": "MD",
        "PH": "PH",
        "VN": "VN",
        "KG": "KG",
        "NG": "NG",
        "IE": "IE",
        "HT": "HT",
        "AR": "AR",
        "MX": "MX",
        "BR": "BR",
        "CY": "CY",
        "PT": "PT",
        "US": "US",
        "MY": "MY",
        "KE": "KE",
        "IL": "IL",
        "KH": "KH",
        "LA": "LA",
        "ZA": "ZA",
        "MA": "MA",
        "DO": "DO",
        "NZ": "NZ",
        "FI": "FI",
        "BA": "BA",
        "CL": "CL",
        "CM (Virtual)": "CM",
        "CA (Virtual)": "CA_V",
        "EG (Virtual)": "EG",
        "GH (Virtual)": "GH",
        "IN (Virtual)": "IN",
        "IQ (Virtual)": "IQ",
        "PK (Virtual)": "PK"
	};
	return countries.hasOwnProperty(country) ? countries[country] : countries["Any"];
};