_SMS.GiveSmsApi.prototype.getRawSite = function(site){
	var sites = {
		"Other": "ot",
        "VK": "vk",
        "WhatsApp": "wa",
        "Viber": "vi",
        "Telegram": "tg",
        "WeChat": "wb",
        "Google": "go",
        "Facebook": "fb",
        "Instagram": "ig",
        "Microsoft": "mm",
        "Twitter": "tw",
        "Uber": "ub",
        "Mail.ru": "ma",
        "Yahoo": "mb",
        "KakaoTalk": "kt",
        "Aol": "pm",
        "Naver": "nv",
        "Avito": "av",
        "Yandex": "ya",
        "Steam": "mt",
        "Tinder": "oi",
        "Mamba": "fd",
        "Imo": "im",
        "TikTok": "lf",
        "Ok.ru": "ok",
        "5ka": "bd",
        "Discord": "ds",
        "ProtonMail": "dp",
        "Grindr": "yw",
        "Gett": "gt",
        "Tencent QQ": "qq",
        "Netflix": "nf",
        "Amazon": "am",
        "CityMobil": "yf",
        "OZON": "sg",
        "BlaBlaCar": "ua",
        "Alibaba": "ab",
        "Nike": "ew",
        "Qiwi": "qw",
        "Youla": "ym",
        "Airbnb": "uk",
        "Yalla": "yl",
        "Perekrestok": "pl",
        "McDonalds": "ry",
        "Delivery Club": "dt",
        "SportMaster": "yk",
        "Careem": "ls",
        "Snapchat": "fu",
        "Bolt": "tx",
        "AliPay": "hw",
        "FoodPanda": "nz",
        "DiDi": "xk",
        "Adidas": "an",
        "Samokat": "jr",
        "BIGO LIVE": "bl",
        "Wildberries": "uu",
        "inDriver": "rl",
        "JD.com": "za",
        "Blizzard": "bz",
        "MVideo": "tk",
        "Vernyi": "nb",
        "Premium.one": "po",
        "Douyin": "lf",
        "PGbonus": "fx",
        "MEGA": "qr",
        "Karusel": "de",
        "MTS CashBack": "da",
        "РСА": "cy",
        "Tango": "xr",
        "Happn": "df",
        "Mail.ru Group": "lb",
        "YouStar": "gb",
        "Aitu": "jj"
	};
	return sites.hasOwnProperty(site) ? sites[site] : sites["Other"];
};