_SMS.GiveSmsApi.prototype.getRawSite = function(site){
	var sites = {
		"Other": "ot",
		"VK": "vk",
		"Ok.ru": "ok",
		"WhatsApp": "wa",
		"Viber": "vi",
		"Telegram": "tg",
		"WeChat": "wb",
		"Google": "go",
		"Avito": "av",
		"Facebook": "fb",
		"Qiwi": "qw",
		"Instagram": "ig",
		"Yandex": "ya",
		"Mail.ru": "ma",
		"Microsoft": "mm",
		"Yahoo": "mb",
		"Aol": "pm",
		"Tinder": "oi",
		"5ka": "bd",
		"Uber": "ub",
		"Amazon": "am",
		"Twitter": "tw",
		"KakaoTalk": "kt",
		"Youla": "ym",
		"Steam": "mt",
		"Gett": "gt",
		"Tencent QQ": "qq",
		"Naver": "nv",
		"Airbnb": "uk",
		"Discord": "ds",
		"Delivery Club": "dt",
		"Bolt": "tx",
		"SportMaster": "yk",
		"McDonalds": "ry",
		"DiDi": "xk",
		"Alibaba": "ab",
		"Mamba": "fd",
		"Yalla": "yl",
		"Premium.one": "po",
		"Netflix": "nf",
		"Imo": "im",
		"TikTok": "lf",
		"Douyin": "lf",
		"ProtonMail": "dp",
		"CityMobil": "yf",
		"PGbonus": "fx",
		"MEGA": "qr",
		"Careem": "ls",
		"BIGO LIVE": "bl",
		"Snapchat": "fu",
		"OZON": "sg",
		"Wildberries": "uu",
		"BlaBlaCar": "ua",
		"Perekrestok": "pl",
		"AliPay": "hw",
		"Karusel": "de",
		"inDriver": "rl",
		"Happn": "df",
		"FoodPanda": "nz",
		"JD.com": "za",
		"MTS CashBack": "da",
		"Nike": "ew",
		"YouStar": "gb",
		"РСА": "cy",
		"Grindr": "yw",
		"Blizzard": "bz",
		"Tango": "xr",
		"MVideo": "tk",
		"Aitu": "jj",
		"Adidas": "an",
		"Samokat": "jr",
		"Vernyi": "nb"
	};
	return _is_nilb(sites[site]) ? sites["Other"] : sites[site]);
};