_SMS.VakSmsApi.prototype.getRawSite = function(site){
	var sites = {
		"VK": "mr",
		"WhatsApp": "wa",
		"Viber": "vi",
		"Telegram": "tg",
		"WeChat": "wc",
		"Facebook": "fb",
		"Instagram": "ig",
		"Microsoft": "ms",
		"Google": "gl",
		"Twitter": "tw",
		"Uber": "ub",
		"Yahoo": "yh",
		"Tinder": "td",
		"KakaoTalk": "kt",
		"Aol": "ao",
		"Naver": "nv",
		"Steam": "st",
		"TikTok": "tk",
		"Avito": "av",
		"LINE Messenger": "lm",
		"Yandex": "ya",
		"Mamba": "mb",
		"Imo": "im",
		"Discord": "dc",
		"Amazon": "am",
		"OLX": "ox",
		"Airbnb": "ab",
		"DrugVokrug": "dv",
		"LinkedIN": "ln",
		"Tencent QQ": "qq",
		"Magnit": "mg",
		"ProtonMail": "pm",
		"BlaBlaCar": "bb",
		"Nike": "nk",
		"Grindr": "gd",
		"DiDi": "dd",
		"Adidas": "ad",
		"Yalla": "ll",
		"Netflix": "nf",
		"OZON": "oz",
		"AliPay": "ap",
		"FoodPanda": "fa",
		"Drom.ru": "dr",
		"PayPal": "pp",
		"DodoPizza": "dp",
		"Taobao": "tb",
		"Apple": "al",
		"Aliexpress": "ai",
		"Qiwi": "qw",
		"MiChat": "mh",
		"SportMaster": "sa",
		"Bolt": "ol",
		"Weibo": "wi",
		"Lenta": "lt",
		"Deliveroo": "do",
		"eBay": "eb",
		"CoinBase": "cb",
		"McDonalds": "md",
		"Craigslist": "crg",
		"MVideo": "mv",
		"SberMarket": "sm",
		"Wildberries": "wb",
		"Burger King": "bk",
		"myGLO": "go",
		"Fiverr": "fr",
		"Vkusvill": "vv",
		"KazanExpress": "ke",
		"METRO": "eo",
		"Twitch": "th",
		"KFC": "kf",
		"Rambler": "rm",
		"PGbonus": "pb",
		"Magnolia": "mn",
		"Monese": "me",
		"Getir": "ge",
		"Vernyi": "vn",
		"Mail.ru Group": "mr",
		"TradingView": "tv",
		"GroupMe": "gm",
		"Kaggle": "kg",
		"OkCupid": "oc",
		"Premium.one": "ta",
		"Douyin": "du",
		"HumbleBundle": "hb",
		"Yubo": "yu",
		"Paysafecard": "pc",
		"Stoloto": "sl",
		"BIP Messenger": "bp",
		"Gojek": "gj",
		"Xiaomi": "xi",
		"MeetMe": "mm",
		"InboxLv": "il",
		"Cita Previa": "ca",
		"Auchan": "au",
		"Revolut": "rt",
		"Okolo": "oa",
		"OVO": "oo",
		"4Fun": "fl",
		"Tokopedia": "tp",
		"Stormgain": "sn",
		"Blockchain": "bc",
		"Signal": "sg",
		"Dana": "dn",
		"Pivko24": "pv",
		"Beget": "bg",
		"WebMoney": "wm",
		"YooMoney": "ym",
		"Badoo": "bd",
		"1Cupis": "cp",
		"Book24": "b24",
		"Marlboro": "mrl",
		"LocalBitcoins": "lb",
		"Lukoil": "lkl",
		"32red": "rd",
		"Tinkoff": "tf",
		"X5 Group": "x5",
		"Rosneft": "rn",
		"Grailed": "gr",
		"Hey_plus": "hs",
		"Plenty of Fish": "pf",
		"Tanuki": "ti",
		"iHerb": "ih",
		"BIGLION": "bl",
		"reg.ru": "rr",
		"profi.ru": "prf",
		"tilda": "tl",
		"Getcontact": "gc",
		"hunter": "ht",
		"ALLES Bonus": "sb",
		"Coinut": "cn",
		"budget4me-34": "bgp",
		"VODOROBOT": "vr",
		"ultra.io": "uo",
		"Foodora": "fo",
		"ogon.ru": "og",
		"Gogym": "gg",
		"Buff.163": "bf",
		"Петрович": "ph",
		"Кошелек": "cm",
		"FriendsClub": "fc",
		"microworkers": "mw",
		"mybeautybonus": "yb",
		"ftx.com": "fx",
		"Dosmart": "dm",
		"Writesonic": "ws",
		"Wmmail": "wl"
	};
	if(!sites.hasOwnProperty(site)){
		this.errorHandler('UNSUPPORTED_SITE', site);
	};
	return sites[site];
};