<div class="container-fluid">
	<%= _.template($('#input_constructor').html())({
		id: "service",
		description: tr("Service"),
		default_selector: "string",
		variants: [
			"sms-activate.ru",
			"smshub.org",
			"5sim.net",
			"365sms.ru",
			"sms-man.ru",
			"getsms.online",
			"cheapsms.ru",
			"smsvk.net",
			"sms.kopeechka.store",
			"smspva.com",
			"simsms.org",
			"onlinesim.ru",
			"sms-acktiwator.ru",
			"vak-sms.com",
			"give-sms.com"
		],
		disable_int: true,
		value_string: "sms-activate.ru",
		help: {
			description: tr("SMS receiving service for which need to get the count of available numbers."),
			examples: [
				{code: "sms-activate.ru", description: "https://sms-activate.ru"},
				{code: "smshub.org", description: "https://smshub.org"},
				{code: "5sim.net", description: "https://5sim.net"}
			]
		}
	}) %>
	<%= _.template($('#input_constructor').html())({
		id: "apiKey",
		description: tr("API key"),
		default_selector: "string",
		disable_int: true,
		value_string: "",
		help: {
			description: tr("API key of the SMS receiving service. The key for the service selected in the \"Service\" parameter. Depending on the service, you can get it in your personal account or in the service settings."),
			examples: [
				{code: "8b1a9953c4611296a827abf8c47804d7"},
				{code: "79916U5718g2266a7bff7fad356c6cb280b3ea"},
				{code: "f4d559ba78aa6c4701c1995ae9977c03"}
			]
		}
	}) %>
	<div class="col-xs-12">
		<form class="form-horizontal">
		  <div class="form-group">
			<div class="col-xs-2">
			  <div class="input-group">
				<span data-preserve="true" data-preserve-type="select" data-preserve-id="site">
				  <select class="form-control input-sm" id="site" placeholder="Site">
					<option value="Other" selected="selected">Other</option>
					<option value="VK">VK</option>
					<option value="WhatsApp">WhatsApp</option>
					<option value="Viber">Viber</option>
					<option value="Telegram">Telegram</option>
					<option value="WeChat">WeChat</option>
					<option value="Google">Google</option>
					<option value="Facebook">Facebook</option>
					<option value="Instagram">Instagram</option>
					<option value="Microsoft">Microsoft</option>
					<option value="Twitter">Twitter</option>
					<option value="Uber">Uber</option>
					<option value="Mail.ru">Mail.ru</option>
					<option value="Yahoo">Yahoo</option>
					<option value="Mamba">Mamba</option>
					<option value="KakaoTalk">KakaoTalk</option>
					<option value="Aol">Aol</option>
					<option value="Naver">Naver</option>
					<option value="Ok.ru">Ok.ru</option>
					<option value="Avito">Avito</option>
					<option value="Yandex">Yandex</option>
					<option value="Steam">Steam</option>
					<option value="Tinder">Tinder</option>
					<option value="Imo">Imo</option>
					<option value="TikTok">TikTok</option>
					<option value="DrugVokrug">DrugVokrug</option>
					<option value="5ka">5ka</option>
					<option value="Discord">Discord</option>
					<option value="ProtonMail">ProtonMail</option>
					<option value="Alibaba">Alibaba</option>
					<option value="Grindr">Grindr</option>
					<option value="Qiwi">Qiwi</option>
					<option value="Gett">Gett</option>
					<option value="LINE Messenger">LINE Messenger</option>
					<option value="Tencent QQ">Tencent QQ</option>
					<option value="Magnit">Magnit</option>
					<option value="Netflix">Netflix</option>
					<option value="Amazon">Amazon</option>
					<option value="CityMobil">CityMobil</option>
					<option value="OZON">OZON</option>
					<option value="BlaBlaCar">BlaBlaCar</option>
					<option value="Nike">Nike</option>
					<option value="Youla">Youla</option>
					<option value="Airbnb">Airbnb</option>
					<option value="MeetMe">MeetMe</option>
					<option value="LinkedIN">LinkedIN</option>
					<option value="Yalla">Yalla</option>
					<option value="Skout">Skout</option>
					<option value="Perekrestok">Perekrestok</option>
					<option value="Drom.ru">Drom.ru</option>
					<option value="DiDi">DiDi</option>
					<option value="McDonalds">McDonalds</option>
					<option value="Adidas">Adidas</option>
					<option value="Samokat">Samokat</option>
					<option value="OLX">OLX</option>
					<option value="Delivery Club">Delivery Club</option>
					<option value="SEOsprint">SEOsprint</option>
					<option value="SportMaster">SportMaster</option>
					<option value="Careem">Careem</option>
					<option value="Snapchat">Snapchat</option>
					<option value="Bolt">Bolt</option>
					<option value="Burger King">Burger King</option>
					<option value="AliPay">AliPay</option>
					<option value="FoodPanda">FoodPanda</option>
					<option value="Papara">Papara</option>
					<option value="eBay">eBay</option>
					<option value="PayPal">PayPal</option>
					<option value="Vernyi">Vernyi</option>
					<option value="Taobao">Taobao</option>
					<option value="HQ Trivia">HQ Trivia</option>
					<option value="POF.com">POF.com</option>
					<option value="ICQ">ICQ</option>
					<option value="MiChat">MiChat</option>
					<option value="Zoho">Zoho</option>
					<option value="Rambler">Rambler</option>
					<option value="BIGO LIVE">BIGO LIVE</option>
					<option value="Wildberries">Wildberries</option>
					<option value="Shopee">Shopee</option>
					<option value="inDriver">inDriver</option>
					<option value="JD.com">JD.com</option>
					<option value="Lenta">Lenta</option>
					<option value="CoinBase">CoinBase</option>
					<option value="Blizzard">Blizzard</option>
					<option value="Grab">Grab</option>
					<option value="MVideo">MVideo</option>
					<option value="Goods">Goods</option>
					<option value="Glovo">Glovo</option>
					<option value="Hezzl">Hezzl</option>
					<option value="Dent">Dent</option>
					<option value="Premium.one">Premium.one</option>
					<option value="Miratorg">Miratorg</option>
					<option value="PGbonus">PGbonus</option>
					<option value="MEGA">MEGA</option>
					<option value="Keybase">Keybase</option>
					<option value="Truecaller">Truecaller</option>
					<option value="Globus">Globus</option>
					<option value="Prom.ua">Prom.ua</option>
					<option value="Magnolia">Magnolia</option>
					<option value="Weibo">Weibo</option>
					<option value="Deliveroo">Deliveroo</option>
					<option value="РСА">РСА</option>
					<option value="YandexGo">YandexGo</option>
					<option value="DodoPizza">DodoPizza</option>
					<option value="Zalo">Zalo</option>
					<option value="LiveScore">LiveScore</option>
					<option value="Tango">Tango</option>
					<option value="Apple">Apple</option>
					<option value="Clubhouse">Clubhouse</option>
					<option value="Lazada">Lazada</option>
					<option value="TradingView">TradingView</option>
					<option value="Kwai">Kwai</option>
					<option value="Fotostrana">Fotostrana</option>
					<option value="1688">1688</option>
					<option value="Kufar.by">Kufar.by</option>
					<option value="Douyin">Douyin</option>
					<option value="EasyPay">EasyPay</option>
					<option value="Wolt">Wolt</option>
					<option value="CliQQ">CliQQ</option>
					<option value="Ticketmaster">Ticketmaster</option>
					<option value="InboxLv">InboxLv</option>
					<option value="NTT Game">NTT Game</option>
					<option value="MyLove">MyLove</option>
					<option value="Karusel">Karusel</option>
					<option value="Happn">Happn</option>
					<option value="RuTube">RuTube</option>
					<option value="MTS CashBack">MTS CashBack</option>
					<option value="PaddyPower">PaddyPower</option>
					<option value="Dostavista">Dostavista</option>
					<option value="Monese">Monese</option>
					<option value="JustDating">JustDating</option>
					<option value="AVON">AVON</option>
					<option value="Craigslist">Craigslist</option>
					<option value="Foody">Foody</option>
					<option value="888casino">888casino</option>
					<option value="WestStein">WestStein</option>
					<option value="OfferUp">OfferUp</option>
					<option value="Faberlic">Faberlic</option>
					<option value="Potato Chat">Potato Chat</option>
					<option value="Amasia">Amasia</option>
					<option value="IQOS">IQOS</option>
					<option value="1xBet">1xBet</option>
					<option value="MOMO">MOMO</option>
					<option value="Douyu">Douyu</option>
					<option value="Uklon">Uklon</option>
					<option value="PingPong">PingPong</option>
					<option value="BitClout">BitClout</option>
					<option value="MapleSEA">MapleSEA</option>
					<option value="Fiverr">Fiverr</option>
					<option value="DetskiyMir">DetskiyMir</option>
					<option value="Aliexpress">Aliexpress</option>
					<option value="Blockchain">Blockchain</option>
					<option value="GameFlip">GameFlip</option>
					<option value="Nimses">Nimses</option>
					<option value="Okey">Okey</option>
					<option value="Signal">Signal</option>
					<option value="TanTan">TanTan</option>
					<option value="TaxiMaxim">TaxiMaxim</option>
					<option value="Beget">Beget</option>
					<option value="WebMoney">WebMoney</option>
					<option value="ZdravCity">ZdravCity</option>
					<option value="Badoo">Badoo</option>
					<option value="Kolesa.kz">Kolesa.kz</option>
					<option value="Onliner.by">Onliner.by</option>
					<option value="Ukrnet">Ukrnet</option>
					<option value="Q12 Trivia">Q12 Trivia</option>
					<option value="Pyro Music">Pyro Music</option>
					<option value="SSOid.net">SSOid.net</option>
					<option value="Olacabs">Olacabs</option>
					<option value="MyMusicTaste">MyMusicTaste</option>
					<option value="Surveytime">Surveytime</option>
					<option value="IVI">IVI</option>
					<option value="Quipp">Quipp</option>
					<option value="KuCoinPlay">KuCoinPlay</option>
					<option value="Wish">Wish</option>
					<option value="Baidu">Baidu</option>
					<option value="Paycell">Paycell</option>
					<option value="Yemeksepeti">Yemeksepeti</option>
					<option value="YouStar">YouStar</option>
					<option value="SneakersnStuff">SneakersnStuff</option>
					<option value="32red">32red</option>
					<option value="ezBuy">ezBuy</option>
					<option value="Rediffmail">Rediffmail</option>
					<option value="Miloan">Miloan</option>
					<option value="Mercado">Mercado</option>
					<option value="Kotak811">Kotak811</option>
					<option value="Hopi">Hopi</option>
					<option value="Trendyol">Trendyol</option>
					<option value="Pairs">Pairs</option>
					<option value="Touchance">Touchance</option>
					<option value="Tosla">Tosla</option>
					<option value="Ininal">Ininal</option>
					<option value="CDKeys">CDKeys</option>
					<option value="MyFishka">MyFishka</option>
					<option value="Huya">Huya</option>
					<option value="Global24">Global24</option>
					<option value="SheerID">SheerID</option>
					<option value="Swvl">Swvl</option>
					<option value="Haraj">Haraj</option>
					<option value="Taksheel">Taksheel</option>
					<option value="Şikayet var">Şikayet var</option>
					<option value="Getir">Getir</option>
					<option value="Cita Previa">Cita Previa</option>
					<option value="Oriflame">Oriflame</option>
					<option value="Wing Money">Wing Money</option>
					<option value="Auchan">Auchan</option>
					<option value="Paxful">Paxful</option>
					<option value="Aitu">Aitu</option>
					<option value="Eneba">Eneba</option>
					<option value="Verse">Verse</option>
					<option value="OnTaxi">OnTaxi</option>
					<option value="Hotline">Hotline</option>
					<option value="Tatneft">Tatneft</option>
					<option value="MoneyLion">MoneyLion</option>
					<option value="Nifty">Nifty</option>
					<option value="Mail.ru Group">Mail.ru Group</option>
					<option value="Rozetka">Rozetka</option>
					<option value="Likee">Likee</option>
					<option value="CityBase">CityBase</option>
					<option value="YouGotaGift">YouGotaGift</option>
					<option value="Dixy">Dixy</option>
					<option value="iCard">iCard</option>
					<option value="IOST">IOST</option>
					<option value="Oracle">Oracle</option>
					<option value="YouDo">YouDo</option>
					<option value="Pandao">Pandao</option>
					<option value="1Cupis">1Cupis</option>
					<option value="Steemit">Steemit</option>
					<option value="Vkusvill">Vkusvill</option>
					<option value="YooMoney">YooMoney</option>
					<option value="Gorzdrav">Gorzdrav</option>
					<option value="Spaces">Spaces</option>
					<option value="FarPost">FarPost</option>
					<option value="Monobank">Monobank</option>
					<option value="NRJ Music Awards">NRJ Music Awards</option>
					<option value="Mos.ru">Mos.ru</option>
					<option value="BillMill">BillMill</option>
					<option value="Okta">Okta</option>
					<option value="Fiqsy">Fiqsy</option>
					<option value="Icrypex">Icrypex</option>
					<option value="Dominos Pizza">Dominos Pizza</option>
					<option value="Payberry">Payberry</option>
					<option value="GlobalTel">GlobalTel</option>
					<option value="Socios">Socios</option>
					<option value="Wmaraci">Wmaraci</option>
					<option value="myGLO">myGLO</option>
					<option value="RosaKhutor">RosaKhutor</option>
					<option value="Kvartplata+">Kvartplata+</option>
					<option value="GG">GG</option>
					<option value="OffGamers">OffGamers</option>
					<option value="Hepsiburada.com">Hepsiburada.com</option>
					<option value="dbrUA">dbrUA</option>
					<option value="Hily">Hily</option>
					<option value="CoinField">CoinField</option>
					<option value="Airtel">Airtel</option>
					<option value="MrGreen">MrGreen</option>
					<option value="Paytm">Paytm</option>
					<option value="Dhani">Dhani</option>
					<option value="CMTcuzdan">CMTcuzdan</option>
					<option value="SnappFood">SnappFood</option>
					<option value="NCsoft">NCsoft</option>
					<option value="Paysend">Paysend</option>
					<option value="E bike Gewinnspiel">E bike Gewinnspiel</option>
					<option value="JKF">JKF</option>
					<option value="Gamer">Gamer</option>
					<option value="99app">99app</option>
					<option value="CAIXA">CAIXA</option>
					<option value="hamrahaval">hamrahaval</option>
					<option value="Gamekit">Gamekit</option>
					<option value="irancell">irancell</option>
					<option value="Alfa">Alfa</option>
					<option value="Disney Hotstar">Disney Hotstar</option>
					<option value="Agroinform">Agroinform</option>
					<option value="HumbleBundle">HumbleBundle</option>
					<option value="CafeBazaar">CafeBazaar</option>
					<option value="cryptocom">cryptocom</option>
					<option value="Gittigidiyor">Gittigidiyor</option>
					<option value="mzadqatar">mzadqatar</option>
					<option value="Algida">Algida</option>
					<option value="Bitaqaty">Bitaqaty</option>
					<option value="Primaries 2020">Primaries 2020</option>
					<option value="Dream11">Dream11</option>
					<option value="Bykea">Bykea</option>
					<option value="Immowelt">Immowelt</option>
					<option value="Digikala">Digikala</option>
					<option value="Yaay">Yaay</option>
					<option value="GameArena">GameArena</option>
					<option value="VitaExpress">VitaExpress</option>
					<option value="Picpay">Picpay</option>
					<option value="Blued">Blued</option>
					<option value="SpotHit">SpotHit</option>
					<option value="Brand20.ua">Brand20.ua</option>
					<option value="Powerkredite">Powerkredite</option>
					<option value="Bisu">Bisu</option>
					<option value="PurePlatfrom">PurePlatfrom</option>
					<option value="Banqi">Banqi</option>
					<option value="Mobile01">Mobile01</option>
					<option value="Humta">Humta</option>
					<option value="Divar">Divar</option>
					<option value="Carousell">Carousell</option>
					<option value="RRSA">RRSA</option>
					<option value="Banks">Banks</option>
					<option value="Skroutz">Skroutz</option>
					<option value="GalaxyWin">GalaxyWin</option>
					<option value="Ziglu">Ziglu</option>
					<option value="Allegro">Allegro</option>
					<option value="Gabi">Gabi</option>
					<option value="Yubo">Yubo</option>
					<option value="iQIYI">iQIYI</option>
					<option value="23red">23red</option>
					<option value="Akelni">Akelni</option>
					<option value="BitTube">BitTube</option>
					<option value="Domdara">Domdara</option>
					<option value="Dukascopy">Dukascopy</option>
					<option value="Electroneum">Electroneum</option>
					<option value="Gcash">Gcash</option>
					<option value="KomandaCard">KomandaCard</option>
					<option value="PUBG">PUBG</option>
					<option value="Winston">Winston</option>
					<option value="FACEIT">FACEIT</option>
					<option value="GPNbonus">GPNbonus</option>
					<option value="Guideh">Guideh</option>
					<option value="Okko">Okko</option>
					<option value="RESO">RESO</option>
					<option value="T7 TAXI">T7 TAXI</option>
					<option value="TamTam">TamTam</option>
					<option value="Tinkoff">Tinkoff</option>
					<option value="PP.UA">PP.UA</option>
					<option value="Pikabu">Pikabu</option>
					<option value="FetLife">FetLife</option>
					<option value="PapaJohns">PapaJohns</option>
					<option value="G2A">G2A</option>
					<option value="Raketa">Raketa</option>
					<option value="LocalBitcoins">LocalBitcoins</option>
					<option value="Lyft">Lyft</option>
					<option value="LYKA">LYKA</option>
					<option value="E-NUM">E-NUM</option>
					<option value="Azino777">Azino777</option>
					<option value="Appbonus">Appbonus</option>
					<option value="WOG.ua">WOG.ua</option>
					<option value="Zadarma">Zadarma</option>
					<option value="Plenty of Fish">Plenty of Fish</option>
					<option value="Skype">Skype</option>
					<option value="Auto.ru">Auto.ru</option>
					<option value="GetResponse">GetResponse</option>
					<option value="Qrooto">Qrooto</option>
					<option value="iHerb">iHerb</option>
					<option value="Sunlight">Sunlight</option>
					<option value="tabor.ru">tabor.ru</option>
					<option value="LDinfo">LDinfo</option>
					<option value="4game">4game</option>
					<option value="Yandex.Eda">Yandex.Eda</option>
					<option value="QIP">QIP</option>
					<option value="Loveplanet">Loveplanet</option>
					<option value="Gem4me">Gem4me</option>
					<option value="ProDoctorov">ProDoctorov</option>
					<option value="ELDORADO">ELDORADO</option>
					<option value="taxify">taxify</option>
					<option value="AdvertApp">AdvertApp</option>
					<option value="ihc.ru">ihc.ru</option>
					<option value="Sprinthost">Sprinthost</option>
					<option value="SPAR">SPAR</option>
					<option value="AKBARS">AKBARS</option>
					<option value="Lukoil">Lukoil</option>
					<option value="PMSM">PMSM</option>
					<option value="Drive2">Drive2</option>
					<option value="parimatch">parimatch</option>
					<option value="Studwork">Studwork</option>
					<option value="Getcontact">Getcontact</option>
					<option value="METRO">METRO</option>
					<option value="ALLES Bonus">ALLES Bonus</option>
					<option value="GoGo">GoGo</option>
					<option value="Coinut">Coinut</option>
					<option value="Sbermarket">Sbermarket</option>
					<option value="1">1</option>
					<option value="679">679</option>
					<option value="1399">1399</option>
					<option value="1950">1950</option>
					<option value="1965">1965</option>
					<option value="2320">2320</option>
					<option value="2838">2838</option>
					<option value="3339">3339</option>
					<option value="4767">4767</option>
					<option value="4938">4938</option>
					<option value="5115">5115</option>
					<option value="5296">5296</option>
					<option value="6996">6996</option>
					<option value="7522">7522</option>
					<option value="7588">7588</option>
					<option value="7764">7764</option>
					<option value="8080">8080</option>
					<option value="8769">8769</option>
					<option value="9138">9138</option>
					<option value="9230">9230</option>
					<option value="100601">100601</option>
					<option value="100602">100602</option>
					<option value="100640">100640</option>
					<option value="100641">100641</option>
					<option value="100642">100642</option>
					<option value="100643">100643</option>
					<option value="PaySend">PaySend</option>
					<option value="Airtel (wf)">Airtel (wf)</option>
					<option value="Azino">Azino</option>
					<option value="Cekkazan">Cekkazan</option>
					<option value="Edgeless">Edgeless</option>
					<option value="Forwarding">Forwarding</option>
					<option value="Get">Get</option>
					<option value="Green">Green</option>
					<option value="LBRY">LBRY</option>
					<option value="Lianxin">Lianxin</option>
					<option value="OkCupid">OkCupid</option>
					<option value="OpenPoint">OpenPoint</option>
					<option value="PayMaya">PayMaya</option>
					<option value="Pokec">Pokec</option>
					<option value="PokerMaster">PokerMaster</option>
					<option value="Reuse">Reuse</option>
					<option value="Ripkord">Ripkord</option>
					<option value="Totalcoin">Totalcoin</option>
					<option value="Uploaded">Uploaded</option>
					<option value="Voopee">Voopee</option>
					<option value="WEKU">WEKU</option>
					<option value="Ace2Three">Ace2Three</option>
					<option value="B4U Cabs">B4U Cabs</option>
					<option value="Bigcash">Bigcash</option>
					<option value="Click Entregas">Click Entregas</option>
					<option value="eZWay">eZWay</option>
					<option value="Flipkart">Flipkart</option>
					<option value="Galaxy">Galaxy</option>
					<option value="Nana">Nana</option>
					<option value="NHSEVEN">NHSEVEN</option>
					<option value="People.com">People.com</option>
					<option value="Protp">Protp</option>
					<option value="Quioo">Quioo</option>
					<option value="Zomato">Zomato</option>
					<option value="2Cupis">2Cupis</option>
					<option value="1Xstavka">1Xstavka</option>
					<option value="Benzuber">Benzuber</option>
					<option value="CreditPlus">CreditPlus</option>
					<option value="Farfor">Farfor</option>
					<option value="Kontur">Kontur</option>
					<option value="MegafonTV">MegafonTV</option>
					<option value="RocketBank">RocketBank</option>
					<option value="Worki">Worki</option>
					<option value="Zaymer">Zaymer</option>
					<option value="ВеликиеИмена.рф">ВеликиеИмена.рф</option>
					<option value="Виктория.рф">Виктория.рф</option>
					<option value="НашЛюбимыйВрач.рф">НашЛюбимыйВрач.рф</option>
					<option value="Почта России">Почта России</option>
					<option value="Zoosk">Zoosk</option>
					<option value="ServerSpace">ServerSpace</option>
					<option value="Apc">Apc</option>
					<option value="Band">Band</option>
					<option value="Up-x.net">Up-x.net</option>
					<option value="BetFair">BetFair</option>
					<option value="CashWalk">CashWalk</option>
					<option value="CONTACT">CONTACT</option>
					<option value="Credit Karma">Credit Karma</option>
					<option value="Dabbl">Dabbl</option>
					<option value="DoorDash">DoorDash</option>
					<option value="FastMail">FastMail</option>
					<option value="Grailed">Grailed</option>
					<option value="Hinge">Hinge</option>
					<option value="Inboxdollars">Inboxdollars</option>
					<option value="Locanto.com">Locanto.com</option>
					<option value="MS Office 365">MS Office 365</option>
					<option value="NetBet">NetBet</option>
					<option value="Neteller">Neteller</option>
					<option value="Postmates">Postmates</option>
					<option value="Skrill">Skrill</option>
					<option value="Streetbees">Streetbees</option>
					<option value="Swagbucks">Swagbucks</option>
					<option value="TAN (micropayment)">TAN (micropayment)</option>
					<option value="The Insiders">The Insiders</option>
					<option value="Twilio">Twilio</option>
					<option value="Venmo">Venmo</option>
					<option value="Weebly">Weebly</option>
					<option value="lino_network">lino_network</option>
					<option value="galaktika">galaktika</option>
					<option value="Hey_plus">Hey_plus</option>
					<option value="Pokermaster">Pokermaster</option>
					<option value="WRIGGLE">WRIGGLE</option>
					<option value="Quidol">Quidol</option>
					<option value="WhatsAround">WhatsAround</option>
					<option value="PlanetaKino">PlanetaKino</option>
					<option value="Sipnet">Sipnet</option>
					<option value="ucoz">ucoz</option>
					<option value="1xStavka">1xStavka</option>
					<option value="HeadHunter">HeadHunter</option>
					<option value="OLIMP">OLIMP</option>
					<option value="Adjarabet">Adjarabet</option>
					<option value="HOMEAWAY">HOMEAWAY</option>
					<option value="Jollychic">Jollychic</option>
					<option value="GoJoy">GoJoy</option>
					<option value="wanmei">wanmei</option>
					<option value="baihe">baihe</option>
					<option value="jiayuan">jiayuan</option>
					<option value="zhenai">zhenai</option>
					<option value="bbs_gfan_com">bbs_gfan_com</option>
					<option value="zhiji">zhiji</option>
					<option value="MiLiao">MiLiao</option>
					<option value="Soul">Soul</option>
					<option value="paopao">paopao</option>
					<option value="lianxin">lianxin</option>
					<option value="Douban">Douban</option>
					<option value="Seagm">Seagm</option>
					<option value="SuYue">SuYue</option>
					<option value="Fordeal">Fordeal</option>
					<option value="Kufar">Kufar</option>
					<option value="Onliner">Onliner</option>
					<option value="zenly">zenly</option>
					<option value="Аптека 36.6">Аптека 36.6</option>
					<option value="kuchenland">kuchenland</option>
					<option value="Pyr_Music">Pyr_Music</option>
					<option value="Webtransfer">Webtransfer</option>
					<option value="OpenI">OpenI</option>
					<option value="LINE">LINE</option>
					<option value="RadugaVkusa">RadugaVkusa</option>
					<option value="brokerby">brokerby</option>
					<option value="masterkey">masterkey</option>
					<option value="ElasticHosts">ElasticHosts</option>
					<option value="VEON">VEON</option>
					<option value="Kaspersky">Kaspersky</option>
					<option value="fex_net">fex_net</option>
					<option value="arumcapital">arumcapital</option>
					<option value="checktrust">checktrust</option>
					<option value="reshigo">reshigo</option>
					<option value="VSK">VSK</option>
					<option value="mql5">mql5</option>
					<option value="Huggies">Huggies</option>
					<option value="zbt">zbt</option>
					<option value="CK_MAKC">CK_MAKC</option>
					<option value="WinLine">WinLine</option>
					<option value="ENNERGIIA">ENNERGIIA</option>
					<option value="Wargaming">Wargaming</option>
					<option value="eToro">eToro</option>
					<option value="NearKitchen">NearKitchen</option>
					<option value="periscope">periscope</option>
					<option value="bitrue">bitrue</option>
					<option value="CoinNess">CoinNess</option>
					<option value="homeaway.nl">homeaway.nl</option>
					<option value="tanuki">tanuki</option>
					<option value="Xiaomi">Xiaomi</option>
					<option value="Stoloto">Stoloto</option>
					<option value="Netease">Netease</option>
					<option value="RUBIKE">RUBIKE</option>
					<option value="TBankrot">TBankrot</option>
					<option value="BitForex">BitForex</option>
					<option value="Ojooo">Ojooo</option>
					<option value="hotmail">hotmail</option>
					<option value="Ceresit">Ceresit</option>
					<option value="MyACUVUE">MyACUVUE</option>
					<option value="TvoyaApteka">TvoyaApteka</option>
					<option value="Wink">Wink</option>
					<option value="GRADUATE">GRADUATE</option>
					<option value="GinzaGO">GinzaGO</option>
					<option value="Technopark">Technopark</option>
					<option value="Sephora">Sephora</option>
					<option value="Flowwow">Flowwow</option>
					<option value="kinoteatr.ru">kinoteatr.ru</option>
					<option value="OKEx">OKEx</option>
					<option value="Таксовичкоф">Таксовичкоф</option>
					<option value="Outbox">Outbox</option>
					<option value="ch1">ch1</option>
					<option value="PageTester">PageTester</option>
					<option value="SMS">SMS</option>
					<option value="SMS4TEST">SMS4TEST</option>
					<option value="SMSINFO">SMSINFO</option>
					<option value="SMSC.RU">SMSC.RU</option>
					<option value="Verify">Verify</option>
					<option value="NXSMS">NXSMS</option>
					<option value="AGENT">AGENT</option>
					<option value="Info">Info</option>
					<option value="PINCD">PINCD</option>
					<option value="MSG">MSG</option>
					<option value="InfoSMS">InfoSMS</option>
					<option value="NemoTV">NemoTV</option>
					<option value="TeleVerify">TeleVerify</option>
					<option value="MZ_Real">MZ_Real</option>
					<option value="Infospika">Infospika</option>
					<option value="1GB">1GB</option>
					<option value="MyArena">MyArena</option>
					<option value="secure_otp">secure_otp</option>
					<option value="Maxim">Maxim</option>
					<option value="NEXMOSMS">NEXMOSMS</option>
					<option value="TeleMSG">TeleMSG</option>
					<option value="MoiKontent">MoiKontent</option>
					<option value="INGOSSTRAKH">INGOSSTRAKH</option>
					<option value="Matroskin">Matroskin</option>
					<option value="NEXMO_SMS">NEXMO_SMS</option>
					<option value="CNET">CNET</option>
					<option value="APPCENT">APPCENT</option>
					<option value="INFORM">INFORM</option>
					<option value="NexmoVerify">NexmoVerify</option>
					<option value="BrEx">BrEx</option>
					<option value="SMS.RU">SMS.RU</option>
					<option value="Dating">Dating</option>
					<option value="UltraVDS">UltraVDS</option>
					<option value="kontur">kontur</option>
					<option value="Chpoking">Chpoking</option>
					<option value="YouDo.com">YouDo.com</option>
					<option value="like4u">like4u</option>
					<option value="SOGAZ">SOGAZ</option>
					<option value="RabotaVGor">RabotaVGor</option>
					<option value="vkserfing">vkserfing</option>
					<option value="Yaplakal">Yaplakal</option>
					<option value="Rutaxi.ru">Rutaxi.ru</option>
					<option value="ULMART">ULMART</option>
					<option value="securegroup">securegroup</option>
					<option value="Topface">Topface</option>
					<option value="AlfaStrah">AlfaStrah</option>
					<option value="Workle">Workle</option>
					<option value="Nexmo">Nexmo</option>
					<option value="Wheely">Wheely</option>
					<option value="HookM">HookM</option>
					<option value="FreelanceRu">FreelanceRu</option>
					<option value="ihorru">ihorru</option>
					<option value="Taxi2412.ru">Taxi2412.ru</option>
					<option value="SMSNotify">SMSNotify</option>
					<option value="YaDlyaVas">YaDlyaVas</option>
					<option value="BEBOO">BEBOO</option>
					<option value="BIGLION">BIGLION</option>
					<option value="рса">рса</option>
					<option value="av100.ru">av100.ru</option>
					<option value="Rus-Telecom">Rus-Telecom</option>
					<option value="Code">Code</option>
					<option value="Maxim.">Maxim.</option>
					<option value="MTService">MTService</option>
					<option value="Usend">Usend</option>
					<option value="PetrI">PetrI</option>
					<option value="SMSCRU">SMSCRU</option>
					<option value="Tiu.ru">Tiu.ru</option>
					<option value="DTINFO">DTINFO</option>
					<option value="WMRFast">WMRFast</option>
					<option value="DIT_EMP">DIT_EMP</option>
					<option value="KFC">KFC</option>
					<option value="taborru">taborru</option>
					<option value="Advance-RP">Advance-RP</option>
					<option value="SMEXPRESS">SMEXPRESS</option>
					<option value="MediaMarkt">MediaMarkt</option>
					<option value="OTTService">OTTService</option>
					<option value="Glamour">Glamour</option>
					<option value="Navigator">Navigator</option>
					<option value="CIAN.RU">CIAN.RU</option>
					<option value="MESSAGE">MESSAGE</option>
					<option value="FISHKA_KFC">FISHKA_KFC</option>
					<option value="IRR.RU">IRR.RU</option>
					<option value="NSMS">NSMS</option>
					<option value="GoAppCash">GoAppCash</option>
					<option value="AUTHMSG">AUTHMSG</option>
					<option value="Spaces.ru">Spaces.ru</option>
					<option value="Camel">Camel</option>
					<option value="GroupPrice">GroupPrice</option>
					<option value="Consultant">Consultant</option>
					<option value="wwwdom2ru">wwwdom2ru</option>
					<option value="PechkaYktRu">PechkaYktRu</option>
					<option value="Ollis">Ollis</option>
					<option value="DDirect_log">DDirect_log</option>
					<option value="VIRTA">VIRTA</option>
					<option value="MS_Verify">MS_Verify</option>
					<option value="InternetSMS">InternetSMS</option>
					<option value="Spacesru">Spacesru</option>
					<option value="BILLmanager">BILLmanager</option>
					<option value="notify">notify</option>
					<option value="awmproxy">awmproxy</option>
					<option value="TelecomInfo">TelecomInfo</option>
					<option value="KonturFocus">KonturFocus</option>
					<option value="teleservice">teleservice</option>
					<option value="WORKZILLA">WORKZILLA</option>
					<option value="PLIVO">PLIVO</option>
					<option value="2domains">2domains</option>
					<option value="ACTION-MCFR">ACTION-MCFR</option>
					<option value="FEBO">FEBO</option>
					<option value="SMSService">SMSService</option>
					<option value="SMC">SMC</option>
					<option value="itunes">itunes</option>
					<option value="Transfer">Transfer</option>
					<option value="1gl">1gl</option>
					<option value="mirznkomstv">mirznkomstv</option>
					<option value="ABC_Center">ABC_Center</option>
					<option value="MCA">MCA</option>
					<option value="FirstVDS">FirstVDS</option>
					<option value="NCC-SMS">NCC-SMS</option>
					<option value="chatvdvoem">chatvdvoem</option>
					<option value="More">More</option>
					<option value="STERH">STERH</option>
					<option value="Mediatech">Mediatech</option>
					<option value="EUROINS">EUROINS</option>
					<option value="Golos25">Golos25</option>
					<option value="Weblancer">Weblancer</option>
					<option value="MirTesen">MirTesen</option>
					<option value="hostinger">hostinger</option>
					<option value="MZReal">MZReal</option>
					<option value="TAXI777">TAXI777</option>
					<option value="WS-MESSAGE">WS-MESSAGE</option>
					<option value="TS_verify">TS_verify</option>
					<option value="Timeweb">Timeweb</option>
					<option value="McHost">McHost</option>
					<option value="REG.RU">REG.RU</option>
					<option value="AtomPark">AtomPark</option>
					<option value="Teamo.ru">Teamo.ru</option>
					<option value="ForexTrend">ForexTrend</option>
					<option value="admiral-xxx">admiral-xxx</option>
					<option value="FASTEN">FASTEN</option>
					<option value="MCHS_112">MCHS_112</option>
					<option value="Banki.ru">Banki.ru</option>
					<option value="Rostelecom">Rostelecom</option>
					<option value="internet">internet</option>
					<option value="PersOffice">PersOffice</option>
					<option value="FORUMHOUSE">FORUMHOUSE</option>
					<option value="Rutaxiru">Rutaxiru</option>
					<option value="MC.KHL.RU">MC.KHL.RU</option>
					<option value="VULKAN.OR">VULKAN.OR</option>
					<option value="ramblermail">ramblermail</option>
					<option value="isms">isms</option>
					<option value="ATinbox">ATinbox</option>
					<option value="ClientMedia">ClientMedia</option>
					<option value="Cenoboy">Cenoboy</option>
					<option value="AGAVA">AGAVA</option>
					<option value="EKSMO">EKSMO</option>
					<option value="webhost1">webhost1</option>
					<option value="ad1">ad1</option>
					<option value="Zenit">Zenit</option>
					<option value="Zetta">Zetta</option>
					<option value="BAT_Info">BAT_Info</option>
					<option value="Sravni.ru">Sravni.ru</option>
					<option value="dwar.ru">dwar.ru</option>
					<option value="ugoria">ugoria</option>
					<option value="chatroulete">chatroulete</option>
					<option value="FRENDI">FRENDI</option>
					<option value="gamekit">gamekit</option>
					<option value="PizzaHut">PizzaHut</option>
					<option value="DNS-SHOP">DNS-SHOP</option>
					<option value="Jino">Jino</option>
					<option value="CoinsUp">CoinsUp</option>
					<option value="Mevius">Mevius</option>
					<option value="CloudLite">CloudLite</option>
					<option value="NETGAME">NETGAME</option>
					<option value="2keys">2keys</option>
					<option value="TAXI">TAXI</option>
					<option value="SERVICE">SERVICE</option>
					<option value="JTI">JTI</option>
					<option value="VernaGroup">VernaGroup</option>
					<option value="IITrust">IITrust</option>
					<option value="Vscale">Vscale</option>
					<option value="1jur">1jur</option>
					<option value="SendPulse">SendPulse</option>
					<option value="NOTICE">NOTICE</option>
					<option value="renins.com">renins.com</option>
					<option value="NAVERLINE">NAVERLINE</option>
					<option value="svyaznoy">svyaznoy</option>
					<option value="VULKANOR">VULKANOR</option>
					<option value="Phone_Code">Phone_Code</option>
					<option value="Nethouse">Nethouse</option>
					<option value="notify_fb">notify_fb</option>
					<option value="Garant">Garant</option>
					<option value="Utkonos">Utkonos</option>
					<option value="Freelance">Freelance</option>
					<option value="admitad">admitad</option>
					<option value="Sobranie">Sobranie</option>
					<option value="SMSINFORM">SMSINFORM</option>
					<option value="Binomo">Binomo</option>
					<option value="FINAM">FINAM</option>
					<option value="Real">Real</option>
					<option value="instaforex">instaforex</option>
					<option value="Atlas-2">Atlas-2</option>
					<option value="THT-CLUB">THT-CLUB</option>
					<option value="Russianpost">Russianpost</option>
					<option value="QGUYS">QGUYS</option>
					<option value="Matbeacom">Matbeacom</option>
					<option value="RouteePin">RouteePin</option>
					<option value="DOTT">DOTT</option>
					<option value="SLOTOKING">SLOTOKING</option>
					<option value="Ticketland">Ticketland</option>
					<option value="Shikari">Shikari</option>
					<option value="eTXTru">eTXTru</option>
					<option value="Zolushka">Zolushka</option>
					<option value="NIVEAMEN">NIVEAMEN</option>
					<option value="sony">sony</option>
					<option value="e1.ru">e1.ru</option>
					<option value="UBU">UBU</option>
					<option value="Proverka">Proverka</option>
					<option value="Hostline">Hostline</option>
					<option value="ngs.ru">ngs.ru</option>
					<option value="Equifax">Equifax</option>
					<option value="Doctor">Doctor</option>
					<option value="Rusinfo">Rusinfo</option>
					<option value="QQTube">QQTube</option>
					<option value="Secure_STMS">Secure_STMS</option>
					<option value="TAXI434343">TAXI434343</option>
					<option value="0674">0674</option>
					<option value="RusTelecom">RusTelecom</option>
					<option value="VPSua">VPSua</option>
					<option value="AVTO-PROFFI">AVTO-PROFFI</option>
					<option value="BIGD.HOST">BIGD.HOST</option>
					<option value="SurfEarner">SurfEarner</option>
					<option value="ISNEXT.RU">ISNEXT.RU</option>
					<option value="WWW.IHC.RU">WWW.IHC.RU</option>
					<option value="Otzovik">Otzovik</option>
					<option value="SmartApe">SmartApe</option>
					<option value="HGCLUB.RU">HGCLUB.RU</option>
					<option value="InfoER">InfoER</option>
					<option value="GameNet">GameNet</option>
					<option value="DIAMOND_RP">DIAMOND_RP</option>
					<option value="Taxi2412ru">Taxi2412ru</option>
					<option value="PROMODJ">PROMODJ</option>
					<option value="INFASEM">INFASEM</option>
					<option value="SlotV">SlotV</option>
					<option value="AzbukaVkusa">AzbukaVkusa</option>
					<option value="FL.ru">FL.ru</option>
					<option value="likestru">likestru</option>
					<option value="CarPrice.ru">CarPrice.ru</option>
					<option value="ImpulsTV">ImpulsTV</option>
					<option value="GSK_UGORIA">GSK_UGORIA</option>
					<option value=".Maxim.">.Maxim.</option>
					<option value="Taxi-Inform">Taxi-Inform</option>
					<option value="e-garant">e-garant</option>
					<option value="MTT">MTT</option>
					<option value="feedgee">feedgee</option>
					<option value="TestDrive">TestDrive</option>
					<option value="frelanchunt">frelanchunt</option>
					<option value="Starbucks">Starbucks</option>
					<option value="ValveVerify">ValveVerify</option>
					<option value="BKAPMAHE">BKAPMAHE</option>
					<option value="CITILINK">CITILINK</option>
					<option value="Frank">Frank</option>
					<option value="RGS">RGS</option>
					<option value="ProtonSMS">ProtonSMS</option>
					<option value="Casebook.ru">Casebook.ru</option>
					<option value="SK_Chulpan">SK_Chulpan</option>
					<option value="informer">informer</option>
					<option value="INFOTEXT">INFOTEXT</option>
					<option value="TeleTrade">TeleTrade</option>
					<option value="firstbyte">firstbyte</option>
					<option value="MEDIASERVIS">MEDIASERVIS</option>
					<option value="Gelios">Gelios</option>
					<option value="AVTOPROFFI">AVTOPROFFI</option>
					<option value="menimobi">menimobi</option>
					<option value="Interfax">Interfax</option>
					<option value="appflow">appflow</option>
					<option value="REGRU">REGRU</option>
					<option value="Ringcaptcha">Ringcaptcha</option>
					<option value="Taxik">Taxik</option>
					<option value="Author24">Author24</option>
					<option value="ZOON.RU">ZOON.RU</option>
					<option value="Azino888">Azino888</option>
					<option value="OOOPSA">OOOPSA</option>
					<option value="TaxSee">TaxSee</option>
					<option value="Frim">Frim</option>
					<option value="Komandir">Komandir</option>
					<option value="glasnru">glasnru</option>
					<option value="RINGCV">RINGCV</option>
					<option value="TheHost">TheHost</option>
					<option value="SalesProces">SalesProces</option>
					<option value="LiveStatus">LiveStatus</option>
					<option value="EPA">EPA</option>
					<option value="STEEM">STEEM</option>
					<option value="AKVAMARIN">AKVAMARIN</option>
					<option value="Vashgolos">Vashgolos</option>
					<option value="HOSTING">HOSTING</option>
					<option value="Action">Action</option>
					<option value="MakeMyBet">MakeMyBet</option>
					<option value="PrivateFX">PrivateFX</option>
					<option value="OPTIMARED">OPTIMARED</option>
					<option value="DANYCC">DANYCC</option>
					<option value="Foodfox">Foodfox</option>
					<option value="MARLBORO">MARLBORO</option>
					<option value="XOCKA">XOCKA</option>
					<option value="Tiuru">Tiuru</option>
					<option value="Revo">Revo</option>
					<option value="GEM">GEM</option>
					<option value="ProstoR">ProstoR</option>
					<option value="Minitax.ru">Minitax.ru</option>
					<option value="MOAB">MOAB</option>
					<option value="Proberry">Proberry</option>
					<option value="PlatformOFD">PlatformOFD</option>
					<option value="LogIn">LogIn</option>
					<option value="GROUPON">GROUPON</option>
					<option value="nlstar.com">nlstar.com</option>
					<option value="Exist.RU">Exist.RU</option>
					<option value="ITIL_Armeec">ITIL_Armeec</option>
					<option value="EuroHoster">EuroHoster</option>
					<option value="Aeroflot">Aeroflot</option>
					<option value="YouMagic">YouMagic</option>
					<option value="EtoDlyaVas">EtoDlyaVas</option>
					<option value="riotech">riotech</option>
					<option value="ABSOLUTINS">ABSOLUTINS</option>
					<option value="ERGO">ERGO</option>
					<option value="ServerDale">ServerDale</option>
					<option value="FastProm">FastProm</option>
					<option value="CardsMobile">CardsMobile</option>
					<option value="RedStar">RedStar</option>
					<option value="boi.pass">boi.pass</option>
					<option value="Balance">Balance</option>
					<option value="PremiaRu">PremiaRu</option>
					<option value="STU">STU</option>
					<option value="clubrs">clubrs</option>
					<option value="RUSONYX">RUSONYX</option>
					<option value="open_i">open_i</option>
					<option value="MGER">MGER</option>
					<option value="Poehali">Poehali</option>
					<option value="OPORA_SK">OPORA_SK</option>
					<option value="DIT_InfoSMS">DIT_InfoSMS</option>
					<option value="RELEVATERU">RELEVATERU</option>
					<option value="mainbox.com">mainbox.com</option>
					<option value="Qsms">Qsms</option>
					<option value="enforta">enforta</option>
					<option value="MediaGramma">MediaGramma</option>
					<option value="VERA">VERA</option>
					<option value="Rusalgrants">Rusalgrants</option>
					<option value="Media_Tele">Media_Tele</option>
					<option value="Clientogram">Clientogram</option>
					<option value="VAMSMS">VAMSMS</option>
					<option value="iNEWS">iNEWS</option>
					<option value="umama">umama</option>
					<option value="Plazius">Plazius</option>
					<option value="AKI">AKI</option>
					<option value="fhunt">fhunt</option>
					<option value="PROFI.RU">PROFI.RU</option>
					<option value=".DS.">.DS.</option>
					<option value="OTP">OTP</option>
					<option value="M1service">M1service</option>
					<option value="OTP_tlsgn">OTP_tlsgn</option>
					<option value="OTPSMS">OTPSMS</option>
					<option value="Ptester">Ptester</option>
					<option value="MCHS">MCHS</option>
					<option value="Investing">Investing</option>
					<option value="olymptrade">olymptrade</option>
					<option value="Onlinetrade">Onlinetrade</option>
					<option value="MediaCenter">MediaCenter</option>
					<option value="slot78">slot78</option>
					<option value="SHCLWH">SHCLWH</option>
					<option value="Selectel">Selectel</option>
					<option value="VPlatinum">VPlatinum</option>
					<option value="didgital-gc">didgital-gc</option>
					<option value="apteka.ru">apteka.ru</option>
					<option value="site">site</option>
					<option value="Smart.Space">Smart.Space</option>
					<option value="crushball">crushball</option>
					<option value="parimatchru">parimatchru</option>
					<option value="sob.ru">sob.ru</option>
					<option value="iatsms">iatsms</option>
					<option value="fixmobile">fixmobile</option>
					<option value="nxverify">nxverify</option>
					<option value="mostbet.com">mostbet.com</option>
					<option value="belkacar">belkacar</option>
					<option value="taovip">taovip</option>
					<option value="matbea.com">matbea.com</option>
					<option value="authentify">authentify</option>
					<option value="pass.media">pass.media</option>
					<option value="qcloud">qcloud</option>
					<option value="digital">digital</option>
					<option value="renins.ru">renins.ru</option>
					<option value="acko">acko</option>
					<option value="znakomstva">znakomstva</option>
					<option value="melbet">melbet</option>
					<option value="letoile">letoile</option>
					<option value="ligastavok">ligastavok</option>
					<option value="vrussia">vrussia</option>
					<option value="aptotsklada">aptotsklada</option>
					<option value="udg">udg</option>
					<option value="freelansim">freelansim</option>
					<option value="liga.pro">liga.pro</option>
					<option value="alyans_pin">alyans_pin</option>
					<option value="msgbrd">msgbrd</option>
					<option value="libertyinfo">libertyinfo</option>
					<option value="picasso">picasso</option>
					<option value="armeec">armeec</option>
					<option value="Twitch">Twitch</option>
					<option value="signalapp">signalapp</option>
					<option value="olimp.bet">olimp.bet</option>
					<option value="sfurf.ru">sfurf.ru</option>
					<option value="uniqlo">uniqlo</option>
					<option value="socialcraft">socialcraft</option>
					<option value="kackad">kackad</option>
					<option value="wifire">wifire</option>
					<option value="doctu.ru">doctu.ru</option>
					<option value="ya888ya">ya888ya</option>
					<option value="list">list</option>
					<option value="sonline">sonline</option>
					<option value="smotreshka">smotreshka</option>
					<option value="eapteka">eapteka</option>
					<option value="smsforall">smsforall</option>
					<option value="gusli">gusli</option>
					<option value="officehq">officehq</option>
					<option value="sistema">sistema</option>
					<option value="myglo">myglo</option>
					<option value="sberfood">sberfood</option>
					<option value="kwork">kwork</option>
					<option value="ips">ips</option>
					<option value="kartavkusa">kartavkusa</option>
					<option value="netpeaksoft">netpeaksoft</option>
					<option value="rgs.ru">rgs.ru</option>
					<option value="lamoda">lamoda</option>
					<option value="24h.tv">24h.tv</option>
					<option value="sushimarket">sushimarket</option>
					<option value="superbro">superbro</option>
					<option value="tatinet.ru">tatinet.ru</option>
					<option value="fastvps">fastvps</option>
					<option value="mylove.ru">mylove.ru</option>
					<option value="kkt.nalog">kkt.nalog</option>
					<option value="youdrive">youdrive</option>
					<option value="ikeafamily">ikeafamily</option>
					<option value="taptaxi">taptaxi</option>
					<option value="serpstat">serpstat</option>
					<option value="alpari">alpari</option>
					<option value="delimobil">delimobil</option>
					<option value="riobet">riobet</option>
					<option value="finspin">finspin</option>
					<option value="limetaxi">limetaxi</option>
					<option value="openbroker">openbroker</option>
					<option value="appcode">appcode</option>
					<option value="propellerad">propellerad</option>
					<option value="glavfinans">glavfinans</option>
					<option value="1cloud">1cloud</option>
					<option value="aviso">aviso</option>
					<option value="tilda">tilda</option>
					<option value="letyshops">letyshops</option>
					<option value="vprognoze">vprognoze</option>
					<option value="startline">startline</option>
					<option value="centrsoobsh">centrsoobsh</option>
					<option value="smsverify">smsverify</option>
					<option value="sessupport">sessupport</option>
					<option value="done_media">done_media</option>
					<option value="megogo">megogo</option>
					<option value="mottor">mottor</option>
					<option value="bytedance">bytedance</option>
					<option value="smsaero.ru">smsaero.ru</option>
					<option value="ao_ock">ao_ock</option>
					<option value="adm.tools">adm.tools</option>
					<option value="pechkaykt">pechkaykt</option>
					<option value="epochtasms">epochtasms</option>
					<option value="bcs">bcs</option>
					<option value="888.ru">888.ru</option>
					<option value="2-berega">2-berega</option>
					<option value="seldon">seldon</option>
					<option value="docdoc">docdoc</option>
					<option value="mmt">mmt</option>
					<option value="getcourse">getcourse</option>
					<option value="pinsms">pinsms</option>
					<option value="superjob">superjob</option>
					<option value="adonis">adonis</option>
					<option value="sutochno.ru">sutochno.ru</option>
					<option value="avtor24">avtor24</option>
					<option value="cis">cis</option>
					<option value="flowwow.com">flowwow.com</option>
					<option value="unit">unit</option>
					<option value="yango">yango</option>
					<option value="pmgroup">pmgroup</option>
					<option value="roboforex">roboforex</option>
					<option value="okcoin">okcoin</option>
					<option value="hunter">hunter</option>
					<option value="brandshop">brandshop</option>
					<option value="mts.invest">mts.invest</option>
					<option value="sms_aero">sms_aero</option>
					<option value="nextmobile">nextmobile</option>
					<option value="taxcom">taxcom</option>
					<option value="bigo">bigo</option>
					<option value="amway">amway</option>
					<option value="otus">otus</option>
					<option value="sonetl">sonetl</option>
					<option value="hh.ru">hh.ru</option>
					<option value="24open.ru">24open.ru</option>
					<option value="like">like</option>
					<option value="love.ru">love.ru</option>
					<option value="telepizza">telepizza</option>
					<option value="bhteam">bhteam</option>
					<option value="elclub">elclub</option>
					<option value="pd">pd</option>
					<option value="huawei">huawei</option>
					<option value="whoosh">whoosh</option>
					<option value="pickpoint">pickpoint</option>
					<option value="x-project">x-project</option>
					<option value="swissborg">swissborg</option>
					<option value="binotrade">binotrade</option>
					<option value="t-business">t-business</option>
					<option value="urentbike">urentbike</option>
					<option value="esportal">esportal</option>
					<option value="coolclever">coolclever</option>
					<option value="nn-card.ru">nn-card.ru</option>
					<option value="localbit">localbit</option>
					<option value="pd39.ru">pd39.ru</option>
					<option value="foodband.ru">foodband.ru</option>
					<option value="Хмельная миля">Хмельная миля</option>
					<option value="Kantar">Kantar</option>
					<option value="babochka">babochka</option>
					<option value="Eleven">Eleven</option>
					<option value="Deal.by">Deal.by</option>
					<option value="Guodulink">Guodulink</option>
					<option value="Технопоинт">Технопоинт</option>
					<option value="iGooods.ru">iGooods.ru</option>
					<option value="Ankama">Ankama</option>
					<option value="CloudFox">CloudFox</option>
					<option value="benzuber">benzuber</option>
					<option value="DeluxePizza">DeluxePizza</option>
					<option value="CityPizza">CityPizza</option>
					<option value="Sushkof">Sushkof</option>
					<option value="888casino.com">888casino.com</option>
					<option value="RESO-MED">RESO-MED</option>
					<option value="FindClone">FindClone</option>
					<option value="Depend">Depend</option>
					<option value="DochkiSin">DochkiSin</option>
					<option value="RBCN">RBCN</option>
					<option value="teender">teender</option>
					<option value="CHAMPION">CHAMPION</option>
					<option value="RBT.ru">RBT.ru</option>
					<option value="lifeair.org">lifeair.org</option>
					<option value="OSTIN">OSTIN</option>
					<option value="neftm">neftm</option>
					<option value="Defile">Defile</option>
					<option value="Meshok.ru">Meshok.ru</option>
					<option value="Rukodelie">Rukodelie</option>
					<option value="GETIR">GETIR</option>
					<option value="Bookmate">Bookmate</option>
					<option value="NapishemCom">NapishemCom</option>
					<option value="Farmlend.ru">Farmlend.ru</option>
					<option value="VYGODA">VYGODA</option>
					<option value="4lapy">4lapy</option>
					<option value="AZS BNP">AZS BNP</option>
					<option value="CrazyCashTV">CrazyCashTV</option>
					<option value="UralAvia">UralAvia</option>
					<option value="MOLNIA">MOLNIA</option>
					<option value="Достаевский">Достаевский</option>
					<option value="TILine">TILine</option>
					<option value="Discoverglo">Discoverglo</option>
					<option value="Nsh-L-Vrach">Nsh-L-Vrach</option>
					<option value="Switips">Switips</option>
					<option value="Доставим">Доставим</option>
					<option value="DDoS-GUARD">DDoS-GUARD</option>
					<option value="broniboy">broniboy</option>
					<option value="Bumble">Bumble</option>
					<option value="Bethowen">Bethowen</option>
					<option value="LEYKA">LEYKA</option>
					<option value="YAMAGUCHI">YAMAGUCHI</option>
					<option value="BondStreet">BondStreet</option>
					<option value="Lite">Lite</option>
					<option value="TNT-PREMIERE">TNT-PREMIERE</option>
					<option value="STAYINTOUCH">STAYINTOUCH</option>
					<option value="Dating4you">Dating4you</option>
					<option value="PMclub">PMclub</option>
					<option value="5eplay">5eplay</option>
					<option value="OSON">OSON</option>
					<option value="TAXI_rus">TAXI_rus</option>
					<option value="SaveTime">SaveTime</option>
					<option value="TaxiNonStop">TaxiNonStop</option>
					<option value="SOKOLOV">SOKOLOV</option>
					<option value="Petshop">Petshop</option>
					<option value="FREEDOM">FREEDOM</option>
					<option value="maxi_retail">maxi_retail</option>
					<option value="STOLICHKI">STOLICHKI</option>
					<option value="Dikidi">Dikidi</option>
					<option value="grani_moscow">grani_moscow</option>
					<option value="zoopt">zoopt</option>
					<option value="RResearch">RResearch</option>
					<option value="Eldfun">Eldfun</option>
					<option value="Almatel">Almatel</option>
					<option value="BETCITY">BETCITY</option>
					<option value="ArenaPlay">ArenaPlay</option>
					<option value="TOMATO">TOMATO</option>
					<option value="SMOTRIM">SMOTRIM</option>
					<option value="pomogatel">pomogatel</option>
					<option value="PIRATPIZZA">PIRATPIZZA</option>
					<option value="Level Kitchen">Level Kitchen</option>
					<option value="mfood">mfood</option>
					<option value="UmnayaMoyka">UmnayaMoyka</option>
					<option value="Denim">Denim</option>
					<option value="MARKETPLACE">MARKETPLACE</option>
					<option value="Pin_up">Pin_up</option>
					<option value="Sneakerandstuff">Sneakerandstuff</option>
					<option value="Upwork">Upwork</option>
					<option value="Passcode">Passcode</option>
					<option value="Haraba">Haraba</option>
					<option value="BetBoom">BetBoom</option>
					<option value="Scaleway">Scaleway</option>
					<option value="ChopChop">ChopChop</option>
					<option value="PolisPrice">PolisPrice</option>
					<option value="LivU">LivU</option>
					<option value="Alfred.repair">Alfred.repair</option>
					<option value="Luxmarket.in.ua">Luxmarket.in.ua</option>
					<option value="Citrus">Citrus</option>
					<option value="Vinted">Vinted</option>
					<option value="nado info">nado info</option>
					<option value="vybeerai">vybeerai</option>
					<option value="PivnoyDvor">PivnoyDvor</option>
					<option value="PmarketinG">PmarketinG</option>
					<option value="senordoner">senordoner</option>
					<option value="ECCO">ECCO</option>
					<option value="SushiBox">SushiBox</option>
					<option value="VRF">VRF</option>
					<option value="Dobrininski">Dobrininski</option>
					<option value="KRUASSANfam">KRUASSANfam</option>
					<option value="alivewater">alivewater</option>
					<option value="Suare">Suare</option>
					<option value="YCLIENTS">YCLIENTS</option>
					<option value="CenterRu">CenterRu</option>
					<option value="5POST">5POST</option>
					<option value="AliSMS">AliSMS</option>
					<option value="Strana2020">Strana2020</option>
					<option value="NinjaPizza">NinjaPizza</option>
					<option value="SHOKO">SHOKO</option>
					<option value="Wekings">Wekings</option>
					<option value="Slotking">Slotking</option>
					<option value="chance">chance</option>
					<option value="TaxiMaster">TaxiMaster</option>
					<option value="SKA">SKA</option>
					<option value="STALAR">STALAR</option>
					<option value="Threema">Threema</option>
					<option value="REST_BAZAR">REST_BAZAR</option>
					<option value="Mrsool">Mrsool</option>
					<option value="PlayerAuctions">PlayerAuctions</option>
					<option value="DOCVED">DOCVED</option>
					<option value="STREET_BEAT">STREET_BEAT</option>
					<option value="getemail">getemail</option>
					<option value="rocketreach">rocketreach</option>
					<option value="bitclout">bitclout</option>
					<option value="KazanExpress">KazanExpress</option>
					<option value="newtonfinance">newtonfinance</option>
					<option value="domclick">domclick</option>
					<option value="MoeZdorovie">MoeZdorovie</option>
					<option value="winstrike">winstrike</option>
					<option value="VseAkcii">VseAkcii</option>
					<option value="moneyplace">moneyplace</option>
					<option value="Nespresso">Nespresso</option>
					<option value="CAOMoscow">CAOMoscow</option>
					<option value="777Origin">777Origin</option>
					<option value="meetme">meetme</option>
					<option value="purse.io">purse.io</option>
					<option value="wap.jamango.ru">wap.jamango.ru</option>
					<option value="nextapp.by">nextapp.by</option>
					<option value="1000taxi.com">1000taxi.com</option>
					<option value="beepcar">beepcar</option>
					<option value="chitai-gorod.ru">chitai-gorod.ru</option>
					<option value="vscale.io">vscale.io</option>
					<option value="AlfaBank">AlfaBank</option>
					<option value="galaxy.mobstudio.ru">galaxy.mobstudio.ru</option>
					<option value="auto.ria.com">auto.ria.com</option>
					<option value="mannabase.com">mannabase.com</option>
					<option value="bilshe.mastercard.ua">bilshe.mastercard.ua</option>
					<option value="viberate.com">viberate.com</option>
					<option value="живёмнасевере.рф">живёмнасевере.рф</option>
					<option value="sipnet.ru">sipnet.ru</option>
					<option value="Dukascopy Connect 911">Dukascopy Connect 911</option>
					<option value="creditkasa.com.ua">creditkasa.com.ua</option>
					<option value="socialtools.ru">socialtools.ru</option>
					<option value="novilidery.com">novilidery.com</option>
					<option value="smart">smart</option>
					<option value="л">л</option>
					<option value="wholeworld.biz">wholeworld.biz</option>
					<option value="k">k</option>
					<option value="pochtabank.ru">pochtabank.ru</option>
					<option value="exchange.musdcoin.com">exchange.musdcoin.com</option>
					<option value="baltika7.ru">baltika7.ru</option>
					<option value="id.sonyentertainmentnetwork.com">id.sonyentertainmentnetwork.com</option>
					<option value="work.ua">work.ua</option>
					<option value="sgro">sgro</option>
					<option value="mail.ukr.net">mail.ukr.net</option>
					<option value="sms-fly.com">sms-fly.com</option>
					<option value="Cash Show">Cash Show</option>
					<option value="smsapi.pl">smsapi.pl</option>
					<option value="b17.ru">b17.ru</option>
					<option value="kab.kpkvozrojdenie.ru">kab.kpkvozrojdenie.ru</option>
					<option value="team50.ru">team50.ru</option>
					<option value="disk.karelia.pro">disk.karelia.pro</option>
					<option value="wmmail.ru">wmmail.ru</option>
					<option value="jugl.net">jugl.net</option>
					<option value="mywallet.net.ua">mywallet.net.ua</option>
					<option value="lino.network">lino.network</option>
					<option value="kegelbum.ru">kegelbum.ru</option>
					<option value="黑加手环">黑加手环</option>
					<option value="upg.ua">upg.ua</option>
					<option value="lk.mgnl.ru">lk.mgnl.ru</option>
					<option value="ASH">ASH</option>
					<option value="NovaPoshta">NovaPoshta</option>
					<option value="app.global24.ua">app.global24.ua</option>
					<option value="11admiral-x.com">11admiral-x.com</option>
					<option value="bigfamily.com.ua">bigfamily.com.ua</option>
					<option value="sweet.tv">sweet.tv</option>
					<option value="smsdatabase">smsdatabase</option>
					<option value="microklad.ru">microklad.ru</option>
					<option value="uplata.ua">uplata.ua</option>
					<option value="petr1.ru">petr1.ru</option>
					<option value="kaggle">kaggle</option>
					<option value="sgroshi.com.ua">sgroshi.com.ua</option>
					<option value="Tengo">Tengo</option>
					<option value="shafa.ua">shafa.ua</option>
					<option value="Moteplassen">Moteplassen</option>
					<option value="Paysafecard">Paysafecard</option>
					<option value="Insurance">Insurance</option>
					<option value="Move">Move</option>
					<option value="Booking">Booking</option>
					<option value="Pingpongx">Pingpongx</option>
					<option value="GroupMe">GroupMe</option>
					<option value="Revolut">Revolut</option>
					<option value="Bunq">Bunq</option>
					<option value="Mozen">Mozen</option>
					<option value="Socpublic">Socpublic</option>
					<option value="Contact-sys">Contact-sys</option>
					<option value="Atlas">Atlas</option>
					<option value="Battle">Battle</option>
					<option value="Boxberry">Boxberry</option>
					<option value="Kinoservisy">Kinoservisy</option>

				  </select>
				</span>
			  </div>
			</div>
			<label class="control-label text-right tr" style="padding-top:5px !important;">Site</label>
		  </div>
		</form>
	</div>
	<%= _.template($('#input_constructor').html())({
		id: "country",
		description: tr("Country"),
		default_selector: "string",
		disable_int: true,
		value_string: "RU",
		variants: [
			"RU<br/><span style='color:gray'>" + tr("Russian Federation") + " (sms-activate.ru, smshub.org, 5sim.net, getsms.online, 365sms.ru, sms-man.ru, sms-reg.com, smspva.com, onlinesim.ru, sms-acktiwator.ru, vak-sms.com)</span>",
			"KZ<br/><span style='color:gray'>" + tr("Kazakhstan") + " (sms-activate.ru, smshub.org, 5sim.net, getsms.online, 365sms.ru, sms-man.ru, sms-reg.com, smspva.com, onlinesim.ru, sms-acktiwator.ru, vak-sms.com)</span>",
			"UA<br/><span style='color:gray'>" + tr("Ukraine") + " (sms-activate.ru, smshub.org, 5sim.net, getsms.online, 365sms.ru, sms-man.ru, sms-reg.com, smspva.com, onlinesim.ru, sms-acktiwator.ru)</span>",
			"GB<br/><span style='color:gray'>" + tr("United Kingdom") + " (sms-activate.ru, smshub.org, 5sim.net, getsms.online, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, sms-acktiwator.ru, vak-sms.com)</span>",
			"PL<br/><span style='color:gray'>" + tr("Poland") + " (sms-activate.ru, smshub.org, 5sim.net, getsms.online, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, vak-sms.com)</span>",
			"EE<br/><span style='color:gray'>" + tr("Estonia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, sms-acktiwator.ru, vak-sms.com)</span>",
			"DE<br/><span style='color:gray'>" + tr("Germany") + " (sms-activate.ru, smshub.org, 5sim.net, getsms.online, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, vak-sms.com)</span>",
			"SE<br/><span style='color:gray'>" + tr("Sweden") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, sms-acktiwator.ru, vak-sms.com)</span>",
			"ID<br/><span style='color:gray'>" + tr("Indonesia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, sms-acktiwator.ru)</span>",
			"LT<br/><span style='color:gray'>" + tr("Lithuania") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, vak-sms.com)</span>",
			"NL<br/><span style='color:gray'>" + tr("Netherlands") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, vak-sms.com)</span>",
			"LV<br/><span style='color:gray'>" + tr("Latvia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, vak-sms.com)</span>",
			"ES<br/><span style='color:gray'>" + tr("Spain") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, vak-sms.com)</span>",
			"FR<br/><span style='color:gray'>" + tr("France") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, vak-sms.com)</span>",
			"MD<br/><span style='color:gray'>" + tr("Moldova") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru, sms-acktiwator.ru)</span>",
			"PH<br/><span style='color:gray'>" + tr("Philippines") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"VN<br/><span style='color:gray'>" + tr("Vietnam") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"KG<br/><span style='color:gray'>" + tr("Kyrgyzstan") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"NG<br/><span style='color:gray'>" + tr("Nigeria") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"HT<br/><span style='color:gray'>" + tr("Haiti") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"RO<br/><span style='color:gray'>" + tr("Romania") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"AR<br/><span style='color:gray'>" + tr("Argentina") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"BY<br/><span style='color:gray'>" + tr("Belarus") + " (sms-activate.ru, smshub.org, 5sim.net, getsms.online, 365sms.ru, sms-man.ru, sms-acktiwator.ru)</span>",
			"MX<br/><span style='color:gray'>" + tr("Mexico") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"BR<br/><span style='color:gray'>" + tr("Brazil") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"CY<br/><span style='color:gray'>" + tr("Cyprus") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"PT<br/><span style='color:gray'>" + tr("Portugal") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, vak-sms.com)</span>",
			"US<br/><span style='color:gray'>" + tr("United States") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"CN<br/><span style='color:gray'>" + tr("China") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, sms-reg.com)</span>",
			"MY<br/><span style='color:gray'>" + tr("Malaysia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com)</span>",
			"KE<br/><span style='color:gray'>" + tr("Kenya") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com)</span>",
			"EG<br/><span style='color:gray'>" + tr("Egypt") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"EG (Virtual)<br/><span style='color:gray'>" + tr("Egypt") + " (smspva.com)</span>",
			"IN<br/><span style='color:gray'>" + tr("India") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"IN (Virtual)<br/><span style='color:gray'>" + tr("India") + " (smspva.com)</span>",
			"KH<br/><span style='color:gray'>" + tr("Cambodia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com)</span>",
			"LA<br/><span style='color:gray'>" + tr("Lao People's Democratic Republic") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com)</span>",
			"CI<br/><span style='color:gray'>" + tr("Cote d'Ivoire") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"YE<br/><span style='color:gray'>" + tr("Yemen") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"ZA<br/><span style='color:gray'>" + tr("South Africa") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com)</span>",
			"CO<br/><span style='color:gray'>" + tr("Colombia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"CA<br/><span style='color:gray'>" + tr("Canada") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"CA (Virtual)<br/><span style='color:gray'>" + tr("Canada") + " (smspva.com)</span>",
			"MA<br/><span style='color:gray'>" + tr("Morocco") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com)</span>",
			"GH<br/><span style='color:gray'>" + tr("Ghana") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"GH (Virtual)<br/><span style='color:gray'>" + tr("Ghana") + " (smspva.com)</span>",
			"UZ<br/><span style='color:gray'>" + tr("Uzbekistan") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, sms-acktiwator.ru)</span>",
			"IQ<br/><span style='color:gray'>" + tr("Iraq") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"IQ (Virtual)<br/><span style='color:gray'>" + tr("Iraq") + " (smspva.com)</span>",
			"AT<br/><span style='color:gray'>" + tr("Austria") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"IR<br/><span style='color:gray'>" + tr("Iran, Islamic Republic of") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"CZ<br/><span style='color:gray'>" + tr("Czech Republic") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"PK<br/><span style='color:gray'>" + tr("Pakistan") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"PK (Virtual)<br/><span style='color:gray'>" + tr("Pakistan") + " (smspva.com)</span>",
			"MN<br/><span style='color:gray'>" + tr("Mongolia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"NP<br/><span style='color:gray'>" + tr("Nepal") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"HN<br/><span style='color:gray'>" + tr("Honduras") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"BO<br/><span style='color:gray'>" + tr("Bolivia, plurinational state of") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"DO<br/><span style='color:gray'>" + tr("Dominican Republic") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, smspva.com)</span>",
			"BF<br/><span style='color:gray'>" + tr("Burkina Faso") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"MM<br/><span style='color:gray'>" + tr("Myanmar") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"IL<br/><span style='color:gray'>" + tr("Israel") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"CD<br/><span style='color:gray'>" + tr("Congo, Democratic Republic of the") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"GM<br/><span style='color:gray'>" + tr("Gambia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"RS<br/><span style='color:gray'>" + tr("Serbia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"CM<br/><span style='color:gray'>" + tr("Cameroon") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"CM (Virtual)<br/><span style='color:gray'>" + tr("Cameroon") + " (smspva.com)</span>",
			"TH<br/><span style='color:gray'>" + tr("Thailand") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"SA<br/><span style='color:gray'>" + tr("Saudi Arabia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"TW<br/><span style='color:gray'>" + tr("Taiwan, Province of China") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"DZ<br/><span style='color:gray'>" + tr("Algeria") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"BD<br/><span style='color:gray'>" + tr("Bangladesh") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"SN<br/><span style='color:gray'>" + tr("Senegal") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"PE<br/><span style='color:gray'>" + tr("Peru") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"GN<br/><span style='color:gray'>" + tr("Guinea") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"ML<br/><span style='color:gray'>" + tr("Mali") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"VE<br/><span style='color:gray'>" + tr("Venezuela") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"AF<br/><span style='color:gray'>" + tr("Afghanistan") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"UG<br/><span style='color:gray'>" + tr("Uganda") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"AO<br/><span style='color:gray'>" + tr("Angola") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"PG<br/><span style='color:gray'>" + tr("Papua New Guinea") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"MZ<br/><span style='color:gray'>" + tr("Mozambique") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"PY<br/><span style='color:gray'>" + tr("Paraguay") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"TN<br/><span style='color:gray'>" + tr("Tunisia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"NI<br/><span style='color:gray'>" + tr("Nicaragua") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"GT<br/><span style='color:gray'>" + tr("Guatemala") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"AE<br/><span style='color:gray'>" + tr("United Arab Emirates") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"ZW<br/><span style='color:gray'>" + tr("Zimbabwe") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"SV<br/><span style='color:gray'>" + tr("El Salvador") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"LY<br/><span style='color:gray'>" + tr("Libyan Arab Jamahiriya") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"JM<br/><span style='color:gray'>" + tr("Jamaica") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"TT<br/><span style='color:gray'>" + tr("Trinidad and Tobago") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"EC<br/><span style='color:gray'>" + tr("Ecuador") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"MR<br/><span style='color:gray'>" + tr("Mauritania") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"SL<br/><span style='color:gray'>" + tr("Sierra Leone") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"BJ<br/><span style='color:gray'>" + tr("Benin") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"BW<br/><span style='color:gray'>" + tr("Botswana") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"GR<br/><span style='color:gray'>" + tr("Greece") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"GY<br/><span style='color:gray'>" + tr("Guyana") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"LR<br/><span style='color:gray'>" + tr("Liberia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"SR<br/><span style='color:gray'>" + tr("Suriname") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"TJ<br/><span style='color:gray'>" + tr("Tajikistan") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"RE<br/><span style='color:gray'>" + tr("Reunion") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"AM<br/><span style='color:gray'>" + tr("Armenia") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"CG<br/><span style='color:gray'>" + tr("Congo") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"GA<br/><span style='color:gray'>" + tr("Gabon") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"BT<br/><span style='color:gray'>" + tr("Bhutan") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"MV<br/><span style='color:gray'>" + tr("Maldives") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"TM<br/><span style='color:gray'>" + tr("Turkmenistan") + " (sms-activate.ru, smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"IE<br/><span style='color:gray'>" + tr("Ireland") + " (5sim.net, 365sms.ru, sms-man.ru, smspva.com, onlinesim.ru)</span>",
			"TR<br/><span style='color:gray'>" + tr("Turkey") + " (sms-activate.ru, 5sim.net, sms-man.ru, onlinesim.ru)</span>",
			"LK<br/><span style='color:gray'>" + tr("Sri Lanka") + " (sms-activate.ru, 5sim.net, sms-man.ru, onlinesim.ru)</span>",
			"IT<br/><span style='color:gray'>" + tr("Italy") + " (sms-activate.ru, 5sim.net, sms-man.ru, smspva.com)</span>",
			"BA<br/><span style='color:gray'>" + tr("Bosnia and Herzegovina") + " (sms-activate.ru, 5sim.net, sms-man.ru, smspva.com)</span>",
			"LB<br/><span style='color:gray'>" + tr("Lebanon") + " (sms-activate.ru, smshub.org, 365sms.ru, sms-man.ru)</span>",
			"HR<br/><span style='color:gray'>" + tr("Croatia") + " (smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"TD<br/><span style='color:gray'>" + tr("Chad") + " (smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"DM<br/><span style='color:gray'>" + tr("Dominica") + " (smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"AW<br/><span style='color:gray'>" + tr("Aruba") + " (smshub.org, 5sim.net, 365sms.ru, sms-man.ru)</span>",
			"AZ<br/><span style='color:gray'>" + tr("Azerbaijan") + " (5sim.net, 365sms.ru, sms-man.ru, onlinesim.ru)</span>",
			"FI<br/><span style='color:gray'>" + tr("Finland") + " (5sim.net, sms-man.ru, smspva.com, vak-sms.com)</span>",
			"US (Virtual)<br/><span style='color:gray'>" + tr("United States") + " (sms-activate.ru, smshub.org, 365sms.ru)</span>",
			"HK<br/><span style='color:gray'>" + tr("Hong Kong") + " (sms-activate.ru, smshub.org, sms-man.ru)</span>",
			"SI<br/><span style='color:gray'>" + tr("Slovenia") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"ET<br/><span style='color:gray'>" + tr("Ethiopia") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"BE<br/><span style='color:gray'>" + tr("Belgium") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"BG<br/><span style='color:gray'>" + tr("Bulgaria") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"HU<br/><span style='color:gray'>" + tr("Hungary") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"TL<br/><span style='color:gray'>" + tr("Timor-Leste") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"CR<br/><span style='color:gray'>" + tr("Costa Rica") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"PR<br/><span style='color:gray'>" + tr("Puerto Rico") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"SD<br/><span style='color:gray'>" + tr("Sudan") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"TG<br/><span style='color:gray'>" + tr("Togo") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"KW<br/><span style='color:gray'>" + tr("Kuwait") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"SZ<br/><span style='color:gray'>" + tr("Eswatini") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"OM<br/><span style='color:gray'>" + tr("Oman") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"SY<br/><span style='color:gray'>" + tr("Syrian Arab Republic") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"QA<br/><span style='color:gray'>" + tr("Qatar") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"PA<br/><span style='color:gray'>" + tr("Panama") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"CU<br/><span style='color:gray'>" + tr("Cuba") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"JO<br/><span style='color:gray'>" + tr("Jordan") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"BB<br/><span style='color:gray'>" + tr("Barbados") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"BI<br/><span style='color:gray'>" + tr("Burundi") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"BS<br/><span style='color:gray'>" + tr("Bahamas") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"GE<br/><span style='color:gray'>" + tr("Georgia") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"GW<br/><span style='color:gray'>" + tr("Guinea-Bissau") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"KM<br/><span style='color:gray'>" + tr("Comoros") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"KN<br/><span style='color:gray'>" + tr("Saint Kitts and Nevis") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"LS<br/><span style='color:gray'>" + tr("Lesotho") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"MW<br/><span style='color:gray'>" + tr("Malawi") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"NA<br/><span style='color:gray'>" + tr("Namibia") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"NE<br/><span style='color:gray'>" + tr("Niger") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"RW<br/><span style='color:gray'>" + tr("Rwanda") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"SK<br/><span style='color:gray'>" + tr("Slovakia") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"BH<br/><span style='color:gray'>" + tr("Bahrain") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"ZM<br/><span style='color:gray'>" + tr("Zambia") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"SO<br/><span style='color:gray'>" + tr("Somalia") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"AL<br/><span style='color:gray'>" + tr("Albania") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"MU<br/><span style='color:gray'>" + tr("Mauritius") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"LU<br/><span style='color:gray'>" + tr("Luxembourg") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"GQ<br/><span style='color:gray'>" + tr("Equatorial Guinea") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"AG<br/><span style='color:gray'>" + tr("Antigua and Barbuda") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"ME<br/><span style='color:gray'>" + tr("Montenegro") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"CH<br/><span style='color:gray'>" + tr("Switzerland") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"ER<br/><span style='color:gray'>" + tr("Eritrea") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"SS<br/><span style='color:gray'>" + tr("South Sudan") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"ST<br/><span style='color:gray'>" + tr("Sao Tome and Principe") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"AI<br/><span style='color:gray'>" + tr("Anguilla") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"MK<br/><span style='color:gray'>" + tr("Macedonia, The Former Yugoslav Republic Of") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"SC<br/><span style='color:gray'>" + tr("Seychelles") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"NC<br/><span style='color:gray'>" + tr("New Caledonia") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"CV<br/><span style='color:gray'>" + tr("Cape Verde") + " (sms-activate.ru, 5sim.net, sms-man.ru)</span>",
			"BM<br/><span style='color:gray'>" + tr("Bermuda") + " (sms-activate.ru, smshub.org, 365sms.ru)</span>",
			"BN<br/><span style='color:gray'>" + tr("Brunei Darussalam") + " (smshub.org, 365sms.ru, sms-man.ru)</span>",
			"CL<br/><span style='color:gray'>" + tr("Chile") + " (5sim.net, sms-man.ru, smspva.com)</span>",
			"NZ<br/><span style='color:gray'>" + tr("New Zealand") + " (5sim.net, sms-man.ru, smspva.com)</span>",
			"PS<br/><span style='color:gray'>" + tr("Palestinian Territory, Occupied") + " (smshub.org, 365sms.ru)</span>",
			"AU<br/><span style='color:gray'>" + tr("Australia") + " (5sim.net, sms-man.ru)</span>",
			"BZ<br/><span style='color:gray'>" + tr("Belize") + " (5sim.net, sms-man.ru)</span>",
			"KY<br/><span style='color:gray'>" + tr("Cayman Islands") + " (5sim.net, sms-man.ru)</span>",
			"DJ<br/><span style='color:gray'>" + tr("Djibouti") + " (5sim.net, sms-man.ru)</span>",
			"GF<br/><span style='color:gray'>" + tr("French Guiana") + " (5sim.net, sms-man.ru)</span>",
			"GD<br/><span style='color:gray'>" + tr("Grenada") + " (5sim.net, sms-man.ru)</span>",
			"GP<br/><span style='color:gray'>" + tr("Guadeloupe") + " (5sim.net, sms-man.ru)</span>",
			"JP<br/><span style='color:gray'>" + tr("Japan") + " (5sim.net, sms-man.ru)</span>",
			"MO<br/><span style='color:gray'>" + tr("Macao") + " (5sim.net, sms-man.ru)</span>",
			"MG<br/><span style='color:gray'>" + tr("Madagascar") + " (5sim.net, sms-man.ru)</span>",
			"MS<br/><span style='color:gray'>" + tr("Montserrat") + " (5sim.net, sms-man.ru)</span>",
			"NO<br/><span style='color:gray'>" + tr("Norway") + " (5sim.net, sms-man.ru)</span>",
			"LC<br/><span style='color:gray'>" + tr("Saint Lucia") + " (5sim.net, sms-man.ru)</span>",
			"VC<br/><span style='color:gray'>" + tr("Saint Vincent and the Grenadines") + " (5sim.net, sms-man.ru)</span>",
			"TZ<br/><span style='color:gray'>" + tr("Tanzania, United Republic Of") + " (5sim.net, sms-man.ru)</span>",
			"UY<br/><span style='color:gray'>" + tr("Uruguay") + " (5sim.net, sms-man.ru)</span>",
			"WS<br/><span style='color:gray'>" + tr("Samoa") + " (5sim.net)</span>",
			"SG<br/><span style='color:gray'>" + tr("Singapore") + " (5sim.net)</span>",
			"SB<br/><span style='color:gray'>" + tr("Solomon Islands") + " (5sim.net)</span>",
			"TO<br/><span style='color:gray'>" + tr("Tonga") + " (5sim.net)</span>",
			"TC<br/><span style='color:gray'>" + tr("Turks and Caicos Islands") + " (5sim.net)</span>",
			"VG<br/><span style='color:gray'>" + tr("Virgin Islands, British") + " (5sim.net)</span>",
			"CF<br/><span style='color:gray'>" + tr("Central African Republic") + " (sms-man.ru)</span>",
			"IS<br/><span style='color:gray'>" + tr("Iceland") + " (sms-man.ru)</span>",
			"MC<br/><span style='color:gray'>" + tr("Monaco") + " (sms-man.ru)</span>"
		],
		help: {
			description: tr("Optional parameter.") + " " + tr("Country of the number."),
			examples: [
				{code: "RU", description: tr("Russian Federation")},
				{code: "UA", description: tr("Ukraine")},
				{code: "US", description: tr("United States")},
				{code: tr("Empty string"), description: tr("Depends on the service used, maybe the last used country or some specific country, you can find out more in the description of the api of the service.")}
			]
		}
	}) %>
	<%= _.template($('#block_start').html())({id:"Additional", name: tr("Additional settings"), description: ""}) %>
		<%= _.template($('#input_constructor').html())({
			id: "customSite",
			description: tr("Custom site"),
			default_selector: "string",
			disable_int: true,
			value_string: "",
			help: {
				description: tr("Optional parameter.") + " " + tr("Custom value of the site, in the form in which it is perceived by the SMS receiving service. If this parameter is specified, then it will be used instead of the \"Site\" parameter and sent to the service without preliminary processing."),
				examples: [
					{code: "wa", description: "WhatsApp"},
					{code: "tg", description: "Telegram"},
					{code: "go", description: "Google"},
					{code: tr("Empty string"), description: tr("Use value from \"") + tr("Site") + tr("\" parameter.")}
				]
			}
		}) %>
		<%= _.template($('#input_constructor').html())({
			id: "customCountry",
			description: tr("Custom country"),
			default_selector: "string",
			disable_int: true,
			value_string: "",
			help: {
				description: tr("Optional parameter.") + " " + tr("Custom value of the country, in the form in which it is perceived by the SMS receiving service. If this parameter is specified, then it will be used instead of the \"Country\" parameter and sent to the service without preliminary processing."),
				examples: [
					{code: "0", description: tr("Russian Federation")},
					{code: "1", description: tr("Ukraine")},
					{code: "187", description: tr("United States")},
					{code: tr("Empty string"), description: tr("Use value from \"") + tr("Country") + tr("\" parameter.")}
				]
			}
		}) %>
		<%= _.template($('#input_constructor').html())({
			id: "serverUrl",
			description: tr("Server url"),
			default_selector: "string",
			disable_int: true,
			value_string: "",
			help: {
				description: tr("Optional parameter.") + " " + tr("Url of the SMS receiving service server. Use this parameter to specify the url of the server, if the required service is not in the list of available ones, but it works through an api similar to the selected service."),
				examples: [
					{code: "https://sms.org"},
					{code: "http://receive-sms.com"},
					{code: "http://127.0.0.1:8888"},
					{code: tr("Empty string"), description: tr("Use default server url, https://sms-activate.ru for sms-activate.ru, etc")}
				]
			}
		}) %>
	<%= _.template($('#block_end').html())() %>
	<%= _.template($('#variable_constructor').html())({
		id: "Save",
		description: tr("Variable to save the result"),
		default_variable: "SMS_NUMBERS_COUNT",
		help: {
			description:tr("Variable in which, after successful execution of the action, the count of available numbers will be written."),
			examples: [
				{code: 137},
				{code: 549},
				{code: 1596}
			]
		}
	}) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Get the count of available numbers on the SMS receiving service.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>