QT -= gui
QT += network websockets
CONFIG += c++17 console
CONFIG -= app_bundle
TARGET = basworker
TEMPLATE = app
DEFINES += QT_DEPRECATED_WARNINGS
INCLUDEPATH += $$PWD $$PWD/../core
DEPENDPATH += $$PWD $$PWD/../core
HEADERS += $$PWD/poolmanager.h $$PWD/devtoolsbridge.h
SOURCES += $$PWD/main.cpp $$PWD/poolmanager.cpp $$PWD/devtoolsbridge.cpp
LIBS += -L$$OUT_PWD/../core/release -lbascore
win32:CONFIG(debug,debug|release): LIBS += -L$$OUT_PWD/../core/debug -lbascore
