<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"FilePath", description: tr("File path"), default_selector: "string", disable_int:true, value_string: "", help: {description:tr("The path to the excel file where for the cell needs to set the style."),examples:[{code:"C:/test.xlsx"},{code:"C:/Program Files/test1.xlsx"},{code:"C:/Program Files/test2.xlsx"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"SheetIndexOrName", description: tr("Sheet index or name"), default_selector: "int", value_number: 0, min_number:0, max_number:999999, help: {description: tr("Index or sheet name in excel file."),examples:[{code:0, description: tr("First sheet index")}, {code:1, description: tr("Second sheet index")}, {code:tr("Sheet1"), description: tr("First sheet name")}, {code:tr("Sheet2"), description: tr("Second sheet name")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"CellAddress", description: tr("Cell address"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Cell address in excel file.") + " " + tr("You can specify a standard address with a column letter and row number, or the column number and row number separated by *."),examples:[{code:"A1", description: tr("First column, first row")}, {code:"B2", description: tr("Second column, second row")}, {code:tr("1*1"), description: tr("Analog") + " A1. " + tr("First column, first row")}, {code:tr("2*2"), description: tr("Analog") + " B2. " + tr("Second column, second row")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"StyleName", description: tr("Style name"), variants:["bold<br/><span style='color:gray;font-size:small'>" + tr("Bold text") + " " + tr("(Value <code>true</code> for bold, <code>false</code> for not bold)") + "</span>","italic<br/><span style='color:gray;font-size:small'>" + tr("Italic text") + " " + tr("(Value <code>true</code> for italic, <code>false</code> for not italic)") + "</span>","underline<br/><span style='color:gray;font-size:small'>" + tr("Underline text") + " " + tr("(Value <code>true</code> for single underline, <code>false</code> for no underline, <code>'double'</code> for double-underline)") + "</span>","strikethrough<br/><span style='color:gray;font-size:small'>" + tr("Strikethrough text") + " " + tr("(Value <code>true</code> for strikethrough <code>false</code> for not strikethrough)") + "</span>"], default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The name of the style which needs to set a value for."),examples:[{code:"bold",description:tr("Bold text")},{code:"italic",description:tr("Italic text")},{code:"underline",description:tr("Underline text")},{code:"strikethrough",description:tr("Strikethrough text")},{code:"subscript",description:tr("Subscript text")},{code:"superscript",description:tr("Superscript text")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"StyleValue", description: tr("Style value"), default_selector: "string", value_string: "", help: {description: tr("The style value which needs to be set.")} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Set style value for cell of excel file.</div>
	<div class="tr tooltip-paragraph-fold">If a resource is specified in the "File path" parameter, resource location will be used.</div>
	<div class="tr tooltip-paragraph-last-fold">If an error occurred while execute action, the thread will stop with fail message. If you want to continue thread, use "Ignore errors" action.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd",use_timeout: true, visible:true}) %>
