<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"FilePath", description: tr("File path"), default_selector: "string", disable_int:true, value_string: "", help: {description:tr("The path to the excel file from which needs to get the cell styles values."),examples:[{code:"C:/test.xlsx"},{code:"C:/Program Files/test1.xlsx"},{code:"C:/Program Files/test2.xlsx"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"SheetIndexOrName", description: tr("Sheet index or name"), default_selector: "int", value_number: 0, min_number:0, max_number:999999, help: {description: tr("Index or sheet name in excel file."),examples:[{code:0, description: tr("First sheet index")}, {code:1, description: tr("Second sheet index")}, {code:tr("Sheet1"), description: tr("First sheet name")}, {code:tr("Sheet2"), description: tr("Second sheet name")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"CellAddress", description: tr("Cell address"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Cell address in excel file.") + " " + tr("You can specify a standard address with a column letter and row number, or the column number and row number separated by *."),examples:[{code:"A1", description: tr("First column, first row")}, {code:"B2", description: tr("Second column, second row")}, {code:tr("1*1"), description: tr("Analog") + " A1. " + tr("First column, first row")}, {code:tr("2*2"), description: tr("Analog") + " B2. " + tr("Second column, second row")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"StylesNameList", description: tr("Style names list"), default_selector: "expression", disable_int:true, value_string: "", help: {description: tr("List of style names which needs to get values."),examples:[{code:"[\"bold\", \"italic\"]"}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"Save", description: tr("Variable to save the result"), default_variable: "XLSX_CELL_STYLES", help: {description: tr("Variable in which, after successful execution of the action, a JSON string containing the names of the styles and their values will be written."),examples:[{code:"{\"bold\":true, \"italic\":true}"}]}}) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Get the cell styles values of the excel file and store them in a variable as a JSON string.</div>
	<div class="tr tooltip-paragraph-fold">The resulting JSON string can be processed using actions from the "JSON" module.</div>
	<div class="tr tooltip-paragraph-last-fold">If an error occurred while execute action, the thread will stop with fail message. If you want to continue thread, use "Ignore errors" action.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd",use_timeout: true, visible:true}) %>
