_SMS.GiveSmsApi.prototype.getRawSite = function(site){
	var sites = {
        "Other": "ot",
        "VK": "vk",
        "WhatsApp": "wa",
        "Viber": "vi",
        "Telegram": "tg",
        "WeChat": "wb",
        "Facebook": "fb",
        "Instagram": "ig",
        "Microsoft": "mm",
        "Google": "go",
        "Twitter": "tw",
        "Uber": "ub",
        "Yahoo": "mb",
        "Tinder": "oi",
        "KakaoTalk": "kt",
        "Aol": "pm",
        "Naver": "nv",
        "Ok.ru": "ok",
        "Mail.ru": "ma",
        "Steam": "mt",
        "TikTok": "lf",
        "Avito": "av",
        "LINE Messenger": "me",
        "Yandex": "ya",
        "Discord": "ds",
        "Amazon": "am",
        "Alibaba": "ab",
        "Airbnb": "uk",
        "LinkedIN": "tn",
        "Tencent QQ": "qq",
        "Magnit": "mg",
        "ProtonMail": "dp",
        "CityMobil": "yf",
        "BlaBlaCar": "ua",
        "Nike": "ew",
        "Grindr": "yw",
        "DiDi": "xk",
        "Adidas": "an",
        "Yalla": "yl",
        "OZON": "sg",
        "AliPay": "hw",
        "PayPal": "ts",
        "DodoPizza": "sd",
        "Apple": "wx",
        "Aliexpress": "hx",
        "Qiwi": "qw",
        "Youla": "ym",
        "Delivery Club": "dt",
        "SportMaster": "yk",
        "Careem": "ls",
        "Bolt": "tx",
        "Weibo": "kf",
        "Lenta": "rd",
        "Blizzard": "bz",
        "MVideo": "tk",
        "Samokat": "jr",
        "SberMarket": "xj",
        "BIGO LIVE": "bl",
        "Wildberries": "uu",
        "Truecaller": "tl",
        "Burger King": "ip",
        "JD.com": "za",
        "myGLO": "ae",
        "Zalo": "mj",
        "Tango": "xr",
        "Amasia": "yo",
        "BitClout": "lt",
        "Vkusvill": "sh",
        "KazanExpress": "ol",
        "METRO": "bv",
        "Twitch": "hb",
        "KFC": "fz",
        "Ticketmaster": "gp",
        "PGbonus": "fx",
        "MEGA": "qr",
        "inDriver": "rl",
        "РСА": "cy",
        "YandexGo": "wf",
        "Mail.ru Group": "lb",
        "Likee": "jf",
        "DetskiyMir": "rj",
        "FACEIT": "qz",
        "ELDORADO": "ke",
        "ZdravCity": "io",
        "Kaggle": "zo",
        "OkCupid": "vm",
        "Premium.one": "po",
        "Douyin": "lf",
        "Happn": "df",
        "MTS CashBack": "da",
        "Baidu": "li",
        "Huya": "pp",
        "SberMegaMarket": "be",
        "RedBook": "qf",
        "Okko": "og",
        "Xiaomi": "yu",
        "X5ID": "bd",
        "Mos.ru": "ce",
        "Karusel": "de",
        "YouStar": "gb",
        "iQIYI": "es",
        "Mocospace": "gm",
        "Switips": "hg",
        "LYKA": "gz",
        "Trip": "nq",
        "SberApteka": "sl",
        "163.com": "wp",
        "Okolo": "yz",
        "Betting": "ft",
        "Megogo": "lv",
        "Twilio": "ee",
        "Lamoda": "sb",
        "Hermes": "en",
        "Wise": "bo",
        "CallApp": "gw",
        "NimoTV": "kz",
        "GalaxyChat": "xe",
        "DewuPoison": "lx",
        "Bilibili": "zs",
        "Taikang": "aw",
        "Wink": "ta",
        "Banks": "md"
    };
	return sites.hasOwnProperty(site) ? sites[site] : sites["Other"];
};