_SMS.SmsPvaApi.prototype.getRawCountry = function(country){
	var countries = {
		"Any": "",
		"RU": "RU",
		"UA": "UA",
		"DE": "DE",
		"IT": "IT",
		"KZ": "KZ",
		"HT": "HT",
		"RO": "RO",
		"AR": "AR",
		"BA": "BA",
		"BR": "BR",
		"KH": "KH",
		"CM (Virtual)": "CM",
		"CA (Virtual)": "CA_V",
		"CL": "CL",
		"CY": "CY",
		"DO": "DO",
		"EG (Virtual)": "EG",
		"EE": "EE",
		"FI": "FI",
		"FR": "FR",
		"GH (Virtual)": "GH",
		"IN (Virtual)": "IN",
		"ID": "ID",
		"IQ (Virtual)": "IQ",
		"IE": "IE",
		"KE": "KE",
		"KG": "KG",
		"LA": "LA",
		"LV": "LV",
		"LT": "LT",
		"MY": "MY",
		"MX": "MX",
		"MD": "MD",
		"MA": "MA",
		"NL": "NL",
		"NZ": "NZ",
		"NG": "NG",
		"PK (Virtual)": "PK",
		"PH": "PH",
		"PL": "PL",
		"PT": "PT",
		"ZA": "ZA",
		"ES": "ES",
		"SE": "SE",
		"GB": "UK",
		"US": "US",
		"VN": "VN"
	};
	return countries.hasOwnProperty(country) ? countries[country] : countries["Any"];
};