_SMS.SmsPvaApi.prototype.getRawSite = function(site){
	var sites = {
		"Other": "opt19",
		"1688": "opt28",
		"32red": "opt97",
		"888casino": "opt22",
		"Adidas": "opt86",
		"Nike": "opt86",
		"Airbnb": "opt46",
		"Alibaba": "opt61",
		"Taobao": "opt61",
		"Amazon": "opt44",
		"Aol": "opt10",
		"Avito": "opt59",
		"Badoo": "opt56",
		"BetFair": "opt25",
		"Blizzard": "opt78",
		"Bolt": "opt81",
		"Burger King": "opt3",
		"Careem": "opt89",
		"CashWalk": "opt122",
		"CityMobil": "opt76",
		"CoinBase": "opt112",
		"CONTACT": "opt51",
		"Craigslist": "opt26",
		"Credit Karma": "opt124",
		"Dabbl": "opt123",
		"Deliveroo": "opt53",
		"DiDi": "opt92",
		"Discord": "opt45",
		"PapaJohns": "opt27",
		"eBay": "opt83",
		"DoorDash": "opt40",
		"Drom.ru": "opt32",
		"DrugVokrug": "opt31",
		"EasyPay": "opt21",
		"Facebook": "opt2",
		"FastMail": "opt43",
		"Fiverr": "opt6",
		"Fotostrana": "opt13",
		"G2A": "opt68",
		"GameFlip": "opt77",
		"Gett": "opt35",
		"Glovo": "opt108",
		"Raketa": "opt108",
		"Google": "opt1",
		"Grab": "opt30",
		"Grailed": "opt420",
		"Grindr": "opt110",
		"Hinge": "opt120",
		"iCard": "opt103",
		"Imo": "opt111",
		"Inboxdollars": "opt118",
		"Instagram": "opt16",
		"JD.com": "opt94",
		"KakaoTalk": "opt71",
		"Lazada": "opt60",
		"LINE Messenger": "opt37",
		"LinkedIN": "opt8",
		"LiveScore": "opt42",
		"LocalBitcoins": "opt105",
		"Locanto.com": "opt114",
		"Lyft": "opt75",
		"LYKA": "opt38",
		"Magnit": "opt126",
		"Mail.ru": "opt33",
		"Mail.ru Group": "opt4",
		"Mamba": "opt100",
		"MeetMe": "opt17",
		"MiChat": "opt96",
		"MOMO": "opt99",
		"Monese": "opt121",
		"MoneyLion": "opt47",
		"MS Office 365": "opt7",
		"Microsoft": "opt15",
		"Naver": "opt73",
		"NetBet": "opt95",
		"Neteller": "opt116",
		"Netflix": "opt101",
		"Ok.ru": "opt5",
		"OfferUp": "opt113",
		"OLX": "opt70",
		"Goods": "opt70",
		"Oracle": "opt115",
		"PaddyPower": "opt109",
		"PayPal": "opt83",
		"POF.com": "opt84",
		"Postmates": "opt91",
		"Prom.ua": "opt107",
		"ProtonMail": "opt57",
		"Shopee": "opt48",
		"Signal": "opt127",
		"Skout": "opt49",
		"Skrill": "opt117",
		"Snapchat": "opt90",
		"SneakersnStuff": "opt119",
		"Steam": "opt58",
		"Streetbees": "opt98",
		"Swagbucks": "opt125",
		"TAN (micropayment)": "opt55",
		"Tango": "opt82",
		"TaxiMaxim": "opt74",
		"Telegram": "opt29",
		"Tencent QQ": "opt34",
		"The Insiders": "opt14",
		"Ticketmaster": "opt52",
		"TikTok": "opt104",
		"Tinder": "opt9",
		"Twilio": "opt66",
		"Twitter": "opt41",
		"Uber": "opt72",
		"Venmo": "opt85",
		"Verse": "opt39",
		"Viber": "opt11",
		"VK": "opt69",
		"WebMoney": "opt24",
		"E-NUM": "opt24",
		"WeChat": "opt67",
		"Weebly": "opt54",
		"WestStein": "opt80",
		"WhatsApp": "opt20",
		"Wing Money": "opt106",
		"Yahoo": "opt65",
		"Yalla": "opt88",
		"Yandex": "opt23",
		"Zoho": "opt93",
		"Qiwi": "opt18"
	};
	return _is_nilb(sites[site]) ? sites["Other"] : sites[site]);
};